account_id = ""
workers_dev = true

[env.development]
name = "solidjs-dev"
route = "dev.solidjs.com/*"

[env.production]
name = "solidjs"
route = "www.solidjs.com/*"

[site]
bucket = "./dist"
entry-point = "workers-site"
