account_id = ""
workers_dev = true

[env.development]
name = "solid-site-dev"
route = "dev.solidjs.com/*"

[env.production]
name = "solid-site"
route = "www.solidjs.com/*"

[site]
pages_build_output_dir = "./dist"
entry-point = "workers-site"
