name = 'solid-site'
main = "./worker.js"
account_id = ""
workers_dev = true
compatibility_date = "2024-09-23"

[assets]
directory = "./dist"
binding = "ASSETS"

[env.development]
name = "solidjs-dev"
route = "dev.solidjs.com/*"

[env.production]
name = "solid-site"
route = "www.solidjs.com/*"
