import { Resource, ResourceCategory, PackageType } from './Ecosystem';

const AUTHOR_MAP = {
  'Aditya Agarwal': { author: 'Aditya Agarwal', author_url: 'https://devadi.netlify.app/' },
  'Aftab Alam': { author: 'Aftab Alam', author_url: 'https://github.com/one-aalam' },
  'Aleksandr Lesnenko': { author: 'Aleksandr Lesnenko', author_url: 'https://github.com/alxnddr' },
  'Alex Lohr': { author: 'Alex Lohr', author_url: 'https://github.com/atk' },
  'Alexandre Mouton Brady': {
    author: 'Alexandre Mouton Brady',
    author_url: 'https://github.com/amoutonbrady',
  },
  'Alexey Kryazhev': { author: 'Alexey Kryazhev', author_url: 'https://github.com/uNmAnNeR' },
  'Alexis H. Munsayac': { author: 'Alexis H. Munsayac', author_url: 'https://github.com/lxsmnsyc' },
  'Amin Yahyaabadi': { author: 'Amin Yahyaabadi', author_url: 'https://github.com/aminya' },
  'Andi Rosca': { author: 'Andi Rosca', author_url: 'https://github.com/andi23rosca' },
  'Ari Seyhun': { author: 'Ari Seyhun', author_url: 'https://github.com/Acidic9' },
  'Arturo Aguilera': { author: 'Arturo Aguilera', author_url: 'https://github.com/aguilera51284' },
  'Aryan Deora': { author: 'Aryan Deora', author_url: 'https://aryandeora.com' },
  bigmistqke: { author: 'bigmistqke', author_url: 'https://github.com/bigmistqke' },
  'Brian Whippo': { author: 'Brian Whippo', author_url: 'https://github.com/SilentRhetoric' },
  'Brendan-csel': { author: 'Brendan-csel', author_url: 'https://github.com/Brendan-csel' },
  'Builder.io': { author: 'Builder.io', author_url: 'https://github.com/builderio' },
  'Cain Atkinson': { author: 'Cain Atkinson', author_url: 'https://github.com/yellowsink' },
  'Caleb Taylor': { author: 'Caleb Taylor', author_url: 'https://github.com/aquaductape' },
  'Carlos Paludetto': { author: 'Carlos Paludetto', author_url: 'https://github.com/ceopaludetto' },
  'Chakra UI': { author: 'chakra-ui', author_url: 'github.com/chakra-ui/' },
  'Chris Czopp': { author: 'Chris Czopp', author_url: 'https://github.com/chris-czopp' },
  CompendiumDevTools: {
    author: 'CompendiumDevTools',
    author_url: 'https://github.com/CompendiumDevTools',
  },
  'Damian Tarnawski': { author: 'Damian Tarnawski', author_url: 'https://github.com/thetarnav' },
  'Daniel Sanchez': { author: 'Daniel Sanchez', author_url: 'https://github.com/thedanchez' },
  'Daniel Still': { author: 'Daniel Still', author_url: 'https://github.com/StillScripts' },
  'David Di Biase': { author: 'David Di Biase', author_url: 'https://github.com/davedbase' },
  DigiChanges: { author: 'DigiChanges', author_url: 'https://github.com/DigiChanges' },
  'Dirag Biswas': { author: 'Dirag Biswas', author_url: 'https://github.com/diragb' },
  'Dmitriy Nikiforov': { author: 'Dmitriy Nikiforov', author_url: 'https://github.com/MrFoxPro' },
  'Eric Fennis': { author: 'Eric Fennis', author_url: 'https://github.com/ericfennis' },
  'Erik C. Forés': { author: 'Erik C. Forés', author_url: 'https://github.com/StudioLambda' },
  'Erik Demaine': { author: 'Erik Demaine', author_url: 'https://github.com/edemaine' },
  'Erik Engi': { author: 'Erik Engi', author_url: 'https://github.com/kireerik' },
  'Erik Verweij': { author: 'Erik Verweij', author_url: 'https://github.com/everweij' },
  'Eugene Matsumura': { author: 'Eugene Matsumura', author_url: 'https://sushiwaumai.github.io/' },
  'Fabien Marie-Louise': {
    author: 'Fabien Marie-Louise',
    author_url: 'https://github.com/fabien-ml',
  },
  'Fabian Hiller': { author: 'Fabian Hiller', author_url: 'https://github.com/fabian-hiller' },
  Fastify: { author: 'Fastify', author_url: 'https://github.com/fastify' },
  flamrdevs: { author: 'flamrdevs', author_url: 'https://github.com/flamrdevs' },
  Flowbite: { author: 'Flowbite', author_url: 'https://flowbite.com/' },
  'François Wouts': { author: 'François Wouts', author_url: 'https://github.com/fwouts' },
  'Gabriel Anderson': { author: 'Gabriel Anderson', author_url: 'https://github.com/andgate' },
  'Gabriel Pureliani': { author: 'Gabriel Pureliani', author_url: 'https://github.com/pureliani' },
  gstatem: { author: 'gstatem', author_url: 'https://github.com/gstatem' },
  'Hervé Verdavaine': { author: 'Hervé Verdavaine', author_url: 'https://github.com/verdavaine' },
  high1: { author: 'high1', author_url: 'https://github.com/high1' },
  'Ignacio Zsabo': { author: 'Ignacio Zsabo', author_url: 'https://github.com/x64Bits' },
  'Ignatius Aditya Setyadi': {
    author: 'Ignatius Aditya Setyadi',
    author_url: 'https://github.com/AdityaSetyadi',
  },
  Inlang: { author: 'Inlang', author_url: 'https://inlang.com' },
  'Ionic Team': { author: 'ionic-team', author_url: 'https://github.com/ionic-team' },
  'Isaac Hagoel': { author: 'Isaac Hagoel', author_url: 'https://github.com/isaacHagoel' },
  'Jack Herrington': { author: 'Jack Herrington', author_url: 'https://github.com/jherr' },
  'Jacob Kofron': { author: 'Jacob Kofron', author_url: 'https://github.com/gnomical' },
  'Jao Austero': { author: 'Jao Austero', author_url: 'https://github.com/jaoaustero' },
  Jasmin: { author: 'Jasmin', author_url: 'https://github.com/GiyoMoon' },
  'Jehaad AL-Johani': { author: 'Jehaad AL-Johani', author_url: 'https://github.com/jehaad1' },
  Jessy: { author: 'Jessy', author_url: 'https://github.com/jessyhq' },
  'Joe Pea': { author: 'Joe Pea', author_url: 'https://github.com/trusktr' },
  'John Carroll': { author: 'John Carroll', author_url: 'https://gitlab.com/john.carroll.p' },
  'Jonathan Ginn': { author: 'Jonathan Ginn', author_url: 'https://gitlab.com/enom' },
  'Joseph Cano': { author: 'Joseph Cano', author_url: 'https://github.com/Jcanotorr06' },
  'Josh Wilson': { author: 'Josh Wilson', author_url: 'https://github.com/joshwilsonvu' },
  'Juanra GM': { author: 'Juanra GM', author_url: 'https://github.com/juanrgm' },
  'Julian Soto': { author: 'Julian Soto', author_url: 'https://github.com/JulianSoto' },
  'Justinas Delinda': { author: 'Justinas Delinda', author_url: 'https://github.com/minht11' },
  'Kai Huebner': { author: 'Kai Huebner', author_url: 'https://github.com/GIShub4' },
  'Kajetan Świątek': { author: 'Kajetan Świątek', author_url: 'https://github.com/kajetansw' },
  'Karthikeyan Ranasthala': {
    author: 'Karthikeyan Ranasthala',
    author_url: 'https://github.com/KarthikeyanRanasthala',
  },
  'Kevin Chen': { author: 'Kevin Chen', author_url: 'https://github.com/xbmlz' },
  'Lily Black': { author: 'Lily Black', author_url: 'https://github.com/L1lith' },
  LUME: { author: 'LUME', author_url: 'https://github.com/lume' },
  'Maciej Kwaśniak': { author: 'Maciej Kwaśniak', author_url: 'https://github.com/Exelord' },
  'Marcos Gonçalves': {
    author: 'Marcos Gonçalves',
    author_url: 'https://github.com/themgoncalves',
  },
  'Martijn Faassen': { author: 'Martijn Faassen', author_url: 'https://github.com/faassen' },
  'Martin Pengelly-Phillips': {
    author: 'Martin Pengelly-Phillips',
    author_url: 'https://github.com/martinpengellyphillips',
  },
  'Mathieu Decaffmeyer': {
    author: 'Mathieu Decaffmeyer',
    author_url: 'https://github.com/mathieuprog',
  },
  'Matteo Bruni': { author: 'Matteo Bruni', author_url: 'https://github.com/matteobruni' },
  'Matthew Ruona': { author: 'Matthew Ruona', author_url: 'https://github.com/rnwonder' },
  'Mauricio Rivera': { author: 'Mauricio Rivera', author_url: 'https://github.com/webblocksapp' },
  'merged-js': { author: 'merged-js', author_url: 'https://github.com/merged-js' },
  Microsoft: { author: 'Microsoft', author_url: 'https://github.com/Microsoft' },
  'Miguel Vieira': { author: 'Miguel Vieira', author_url: 'https://github.com/miguelsalesvieira' },
  'Mike Ledger': { author: 'Mike Ledger', author_url: 'https://github.com/mikeplus64' },
  'Mikkel Ringaud': { author: 'Mikkel Ringaud', author_url: 'https://github.com/Vexcited' },
  'Mohammad Bagher Abiyat': {
    author: 'Mohammad Bagher Abiyat',
    author_url: 'https://github.com/Aslemammad',
  },
  'Moshe Uminer': { author: 'Moshe Uminer', author_url: 'https://github.com/mosheduminer' },
  'Neil Chudleigh': { author: 'Neil Chudleigh', author_url: 'https://github.com/nchudleigh' },
  nextauthjs: { author: 'nextauthjs', author_url: 'https://github.com/nextauthjs' },
  'Nick Saunders': { author: 'Nick Saunders', author_url: 'https://github.com/nsaunders' },
  'Nikhil Saraf': { author: 'Nikhil Saraf', author_url: 'https://gitlab.com/nksaraf' },
  'Olivier Gamache': { author: 'Olivier Gamache', author_url: 'https://gitlab.com/olgam4' },
  'Oren Elbaum': { author: 'Oren Elbaum', author_url: 'https://github.com/orenelbaum' },
  OrJDev: { author: 'OrJDev', author_url: 'https://github.com/OrJDev' },
  'Pablo Berganza': { author: 'Pablo Berganza', author_url: 'https://github.com/pablo-abc' },
  'Paul Heggeseth': { author: 'Paul Heggeseth', author_url: 'https://github.com/pheggeseth' },
  PDFSlick: { author: 'PDFSlick', author_url: 'https://github.com/pdfslick/' },
  'Prince Neil Cedrick Castro': {
    author: 'Prince Neil Cedrick Castro',
    author_url: 'https://github.com/git-ced',
  },
  'Raqueebuddin Aziz': { author: 'Raqueebuddin Aziz', author_url: 'https://raqueebuddinaziz.com/' },
  'Reinaldy Rafli': { author: 'Reinaldy Rafli', author_url: 'https://github.com/aldy505' },
  'Robert Soriano': { author: 'Robert Soriano', author_url: 'https://github.com/wobsoriano' },
  'Ryan Carniato': { author: 'Ryan Carniato', author_url: 'https://github.com/ryansolid' },
  'Ryan Turnquist': { author: 'Ryan Turnquist', author_url: 'https://github.com/rturnq' },
  'Sagar Poudel': { author: 'Sagar Poudel', author_url: 'https://github.com/poudels14' },
  'Sanich Kotikov': { author: 'SanichKotikov', author_url: 'https://github.com/SanichKotikov' },
  sect: { author: 'sect', author_url: 'https://github.com/sectsect' },
  'Sergey Shishkin': { author: 'Sergey Shishkin', author_url: 'https://github.com/shishkin' },
  'Simon Holmes': { author: 'Simon Holmes', author_url: 'https://github.com/srsholmes' },
  'Simone Mastromattei': {
    author: 'Simone Mastromattei',
    author_url: 'https://github.com/smastrom',
  },
  skrylnikov: { author: 'skrylnikov', author_url: 'https://github.com/skrylnikov' },
  specialdoom: { author: 'specialdoom', author_url: 'https://github.com/specialdoom' },
  'Sukhpreet Singh': { author: 'Sukhpreet Singh', author_url: 'https://github.com/sacarvy' },
  Swiper: { author: 'Swiper', author_url: 'https://swiperjs.com' },
  swise0: { author: 'swise0', author_url: 'https://github.com/swise0' },
  T6: { author: 'T6', author_url: 'https://github.com/tjjfvi' },
  Tanstack: { author: 'Tanstack', author_url: 'https://www.tanstack.com/' },
  'Tanvesh Sarve': { author: 'Tanvesh Sarve', author_url: 'https://github.com/tanvesh01' },
  thednp: { author: 'thednp', author_url: 'https://github.com/thednp' },
  'Tiago Cavalcante': {
    author: 'Tiago Cavalcante',
    author_url: 'https://github.com/TiagoCavalcante',
  },
  'Travis Waith-Mair': { author: 'Travis Waith-Mair', author_url: 'https://github.com/Jarvis1010' },
  Tronikelis: { author: 'Tronikelis', author_url: 'https://github.com/Tronikelis' },
  'Vladislav Lipatov': { author: 'Vladislav Lipatov', author_url: 'https://github.com/elite174' },
  'Vyacheslav Azarenko': {
    author: 'Vyacheslav Azarenko',
    author_url: 'https://github.com/s0ftik3',
  },
  'William Berglund': { author: 'William Berglund', author_url: 'https://github.com/functorism' },
  'Wilton Silva': { author: 'Wilton Silva', author_url: 'https://github.com/niliadu' },
  Wundergraph: { author: 'Wundergraph', author_url: 'https://wundergraph.com' },
  'Xavier Loh': { author: 'Xavier Loh', author_url: 'https://github.com/otonashixav' },
  'Yonatan Bendahan': { author: 'Yonatan Bendahan', author_url: 'https://github.com/yonathan06' },
} as const;

type Author = keyof typeof AUTHOR_MAP;

/** Creates a resource entry of type `Package` with the author details injected  */
const packageBy = (
  author: Author,
  resource: Omit<Resource, 'author' | 'author_url' | 'type'>,
): Resource => ({
  ...resource,
  ...AUTHOR_MAP[author],
  type: PackageType.Package,
});

/** Creates a resource entry of type `Library` with the author details injected  */
const libraryBy = (
  author: Author,
  resource: Omit<Resource, 'author' | 'author_url' | 'type'>,
): Resource => ({
  ...resource,
  ...AUTHOR_MAP[author],
  type: PackageType.Library,
});

const utilities: Array<Resource> = [
  packageBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/solid-styled-jsx',
    title: 'solid-styled-jsx',
    description: "Wrapper for using Solid with Vercel's Styled JSX.",
    keywords: ['vercel', 'styled', 'jsx'],
    official: true,
    categories: [ResourceCategory.Routers],
  }),
  {
    link: 'https://github.com/solidjs/solid-router',
    title: 'solid-router',
    description:
      'Universal router for SolidJS, combining paradigms of React Router and Ember Router. Supports JSX or JSON routing, and nested routes. Part of Solid Start, making it the official router.',
    author: 'Ryan Carniato and Ryan Turnquist',
    author_url: 'https://github.com/ryansolid',
    keywords: ['router'],
    official: true,
    type: PackageType.Package,
    categories: [ResourceCategory.Routers],
  },
  packageBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/solid/blob/main/packages/solid-element',
    title: 'solid-element',
    description: 'Extensions to Solid.js that add a Web Component wrapper.',
    keywords: ['web', 'components', 'web components', 'elements'],
    official: true,
    categories: [ResourceCategory.Routers],
  }),
  {
    link: 'https://github.com/milahu/solidjs-treeview-component',
    title: 'solidjs-treeview-component',
    description: 'Interactive tree of nodes, expand/collapse, fetch child nodes on demand.',
    author: 'milahu',
    author_url: 'https://github.com/milahu',
    keywords: ['tree', 'expand', 'collapse'],
    official: false,
    type: PackageType.Package,
    categories: [ResourceCategory.Routers],
  },
  packageBy('Mike Ledger', {
    link: 'https://github.com/mikeplus64/solid-typefu-router5',
    title: 'solid-typefu-router5',
    description:
      'This package provides a router with integration with router5 and solid-js, and features type safe router and link creation.',
    keywords: ['router'],
    official: false,
    categories: [ResourceCategory.Routers],
    maintained: false,
  }),
  packageBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/solid-meta',
    title: 'solid-meta',
    description: 'Asynchronous SSR-ready Document Head management for Solid based on React Head.',
    keywords: ['meta', 'document'],
    official: true,
    categories: [ResourceCategory.Plugins],
  }),
  packageBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/solid-refresh',
    title: 'solid-refresh',
    description: 'This project aims to provide HMR for Solid for various bundlers.',
    keywords: ['hmr', 'refresh'],
    official: true,
    categories: [ResourceCategory.Plugins],
  }),
  libraryBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/solid-jest',
    title: 'solid-jest',
    description:
      'This library contains presets for SolidJS to easily get started testing with Jest for both browser and server rendering with Node.',
    keywords: ['testing', 'jest'],
    official: true,
    categories: [ResourceCategory.Testing],
    maintained: false,
  }),
  libraryBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/solid-testing-library',
    title: 'solid-testing-library',
    description:
      'Simple and complete Solid DOM testing utilities that encourage good testing practices.',
    keywords: ['testing'],
    official: true,
    categories: [ResourceCategory.Testing],
  }),
  packageBy('Damian Tarnawski', {
    link: 'https://github.com/thetarnav/solid-devtools',
    title: 'Solid Developer Tools',
    description:
      'Library of developer tools, reactivity debugger & Devtools Chrome extension for visualizing SolidJS reactivity graph.',
    keywords: ['debug', 'devtools'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
  }),
  packageBy('Alexandre Mouton Brady', {
    link: 'https://github.com/solidjs/solid-playground',
    title: 'solid-playground',
    description: 'A playground and REPL for Solid.',
    keywords: ['playground', 'plugin'],
    official: true,
    categories: [ResourceCategory.AddOn],
  }),
  packageBy('Alexandre Mouton Brady', {
    link: 'https://github.com/amoutonbrady/solid-heroicons',
    title: 'solid-heroicons',
    description: 'A convenient port of the Tailwind Heroicons.',
    keywords: ['icons', 'ui', 'hero'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
  }),
  packageBy('Ignacio Zsabo', {
    link: 'https://github.com/x64Bits/solid-icons',
    title: 'solid-icons',
    description: 'The simplest way to use icons in SolidJS',
    keywords: ['icons', 'svg', 'iconpack'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
  }),
  packageBy('Alexandre Mouton Brady', {
    link: 'https://github.com/amoutonbrady/esbuild-plugin-solid',
    title: 'esbuild-plugin-solid',
    description: 'Plugin to compile solid-js jsx components with esbuild.',
    keywords: ['esbuild', 'tooling'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
  }),
  packageBy('Ryan Carniato', {
    link: 'https://github.com/ryansolid/dom-expressions/tree/main/packages/lit-dom-expressions',
    title: 'lit-dom-expressions',
    description: 'Tagged Template Literal API for DOM Expressions.',
    keywords: ['babel', 'expressions'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
  }),
  packageBy('Ryan Carniato', {
    link: 'https://github.com/ryansolid/dom-expressions/tree/main/packages/babel-plugin-jsx-dom-expressions',
    title: 'babel-plugin-jsx-dom-expressions',
    description: 'Babel plugin that converts JSX to DOM Expressions.',
    keywords: ['babel', 'expressions'],
    official: true,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
  }),
  packageBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/create-solid',
    title: 'create-solid',
    description: "Solid's port of Create React App.",
    keywords: ['starter', 'cra'],
    official: true,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
    maintained: false,
  }),
  libraryBy('Ryan Carniato', {
    link: 'https://github.com/ryansolid/dom-expressions',
    title: 'dom-expressions',
    description:
      'The renderer behind Solid.js that enables lightning fast fine grained performance.',
    keywords: ['dom', 'expressions'],
    official: true,
    categories: [ResourceCategory.BuildUtilities],
  }),
  packageBy('high1', {
    link: 'https://github.com/high1/solid-typescript-rollup',
    title: 'solid-typescript-rollup',
    description: 'Solid and Rollup support starter.',
    keywords: ['starter', 'rollup'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
    maintained: false,
  }),
  packageBy('Jonathan Ginn', {
    link: 'https://gitlab.com/enom/solid-parcel-starter',
    title: 'solid-parcel-starter',
    description: 'Solid starter with Tailwind and Parcel',
    keywords: ['starter', 'typescript', 'parcel', 'tailwind'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
    maintained: false,
  }),
  packageBy('Alexandre Mouton Brady', {
    link: 'https://github.com/amoutonbrady/solid-snowpack-starter',
    title: 'solid-snowpack-starter',
    description:
      'Solid + snowpack + tailwindcss template You get HMR out of the box and full PWA compatible.',
    keywords: ['starter', 'typescript', 'snowpack'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
    maintained: false,
  }),
  packageBy('Builder.io', {
    link: 'https://github.com/builderio/jsx-lite',
    title: 'jsx-lite',
    description:
      'Generalized JSX that transpiles into Solid, React, Angular, Vue, etc. They have plugins for Figma, VSCode, & Builder.io.',
    keywords: ['jsx', 'jsx-lite', 'builder'],
    official: true,
    categories: [ResourceCategory.BuildUtilities],
  }),
  libraryBy('high1', {
    link: 'https://github.com/high1/solid-typescript-starter',
    title: 'solid-typescript-starter',
    description: 'Typescript start with Solid.',
    keywords: ['starter', 'typescript'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
    maintained: false,
  }),
  libraryBy('Ryan Carniato', {
    link: 'https://github.com/ryansolid/solid-ts-webpack',
    title: 'solid-ts-webpack',
    description: 'Typescript start with Webpack.',
    keywords: ['starter', 'typescript', 'webpack'],
    official: true,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
  }),
  libraryBy('Alexandre Mouton Brady', {
    link: 'https://github.com/solidjs/templates',
    title: 'solidjs/templates',
    description: 'This repository holds most of the official starter templates for vite.',
    keywords: ['starter', 'templates', 'vite', 'tailwind', 'bootstrap'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
  }),
  packageBy('Alexandre Mouton Brady', {
    link: 'https://github.com/amoutonbrady/snowpack-solid',
    title: 'snowpack-solid',
    description:
      'Solid + snowpack + tailwindcss template You get HMR out of the box and full PWA compatible.',
    keywords: ['snowpack', 'tooling'],
    official: false,
    categories: [ResourceCategory.Starters],
    maintained: false,
  }),
  packageBy('Alexandre Mouton Brady', {
    link: 'https://github.com/amoutonbrady/parcel2-solid-ts-starter',
    title: 'parcel2-solid-ts-starter',
    description:
      'Minimal Solid starter based on yarn 2 pnp resolution (zero-install) and parcel 2 for bundling.',
    keywords: ['parcel2', 'tooling', 'boilerplate'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
    maintained: false,
  }),
  packageBy('Dmitriy Nikiforov', {
    link: 'https://github.com/MrFoxPro/solid-rollup-boilerplate',
    title: 'solid-rollup-boilerplate',
    description: 'Simple starter for Rollup + Solid.',
    keywords: ['boilerplate', 'rollup'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
    maintained: false,
  }),
  packageBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/solid-transition-group',
    title: 'solid-transition-group',
    description:
      'Animation library influenced by React Transition Group and Vue Transitions for the SolidJS library.',
    keywords: ['transitions', 'animations'],
    official: true,
    categories: [ResourceCategory.AddOn],
  }),
  libraryBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/solid-start',
    title: 'solid-start',
    description:
      'This is the home of the new official starter for Solid. This is still a work in progress.',
    keywords: ['starter'],
    official: true,
    categories: [ResourceCategory.AddOn],
  }),
  packageBy('Alexandre Mouton Brady', {
    link: 'https://github.com/solidjs/vite-plugin-solid',
    title: 'vite-plugin-solid',
    description: 'Plugin that allows SolidJS to run with Vite.',
    keywords: ['vite', 'bundler'],
    official: true,
    categories: [ResourceCategory.BuildUtilities, ResourceCategory.Plugins],
  }),
  packageBy('Martin Pengelly-Phillips', {
    link: 'https://github.com/thisbeyond/solid-dnd',
    title: 'solid-dnd',
    description: 'A lightweight and extremely performant drag and drop toolkit for Solid.',
    keywords: ['drag', 'drop', 'dnd'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.Primitives],
  }),
  packageBy('Daniel Sanchez', {
    link: 'https://github.com/thedanchez/swapy-solid',
    title: 'swapy-solid',
    description: 'Solid components enabling drag and swap layouts via Swapy.',
    keywords: ['drag', 'drop', 'swap', 'swapy', 'solid'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/react-solid-state',
    title: 'react-solid-state',
    description: 'React Hooks API to use Solid.js paradigm in your existing React apps.',
    keywords: ['hooks'],
    official: false,
    categories: [ResourceCategory.AddOn],
  }),
  packageBy('skrylnikov', {
    link: 'https://github.com/skrylnikov/reatom-solid',
    title: 'reatom-solid',
    description: 'Solid bindings for Reatom store.',
    keywords: ['reatom'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.Data],
    maintained: false,
  }),
  {
    link: 'https://github.com/storeon/solidjs',
    title: 'solid-storeon',
    description:
      'A package that helps to connect store with Solid.js to provide a better performance and developer experience while remaining so tiny.',
    author: 'Storeon',
    keywords: ['storeon', 'store'],
    official: false,
    type: PackageType.Package,
    categories: [ResourceCategory.AddOn, ResourceCategory.Data],
    maintained: false,
  },
  {
    link: 'https://github.com/effector/effector/tree/master/packages/effector-solid',
    title: 'effector-solid',
    description:
      'A package that adapts effector units for perfect SolidJS performance with updates batching.',
    author: 'effector',
    keywords: ['effector', 'state', 'store', 'unit', 'effect', 'manager'],
    official: false,
    type: PackageType.Package,
    categories: [ResourceCategory.AddOn, ResourceCategory.Data],
  },
  packageBy('Ryan Carniato', {
    link: 'https://github.com/solidjs/solid-styled-components',
    title: 'solid-styled-components',
    description:
      'This library provides Styled Components and css helper found in popular JS in CSS libraries.',
    keywords: ['styled', 'components', 'goober'],
    official: true,
    categories: [ResourceCategory.AddOn],
  }),
  packageBy('Ari Seyhun', {
    link: 'https://github.com/Acidic9/emotion-solid',
    title: 'emotion-solid',
    description: 'This library is an Emotion Styled port for Solid.',
    keywords: ['emotion', 'styled', 'components', 'css in js'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
  }),
  packageBy('Gabriel Anderson', {
    link: 'https://github.com/andgate/solid-orbit',
    title: 'solid-orbit',
    description:
      'This package provides Solid a provider and hooks for Orbit. Most notably, this provides a useQuery hook which is a query transform listener, updating component props with records as they are changed.',
    keywords: ['orbit', 'store', 'data'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.Data],
  }),
  packageBy('Joe Pea', {
    link: 'https://github.com/lume/lume',
    title: 'LUME',
    description:
      'Custom elements powered by Solid. LUME is a toolkit that creates 2D or 3D experiences for any device from mobile to desktop to AR/VR.',
    keywords: ['graphics', '3d', 'ui'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
  }),
  packageBy('Arturo Aguilera', {
    link: 'https://www.npmjs.com/package/phosphor-solid',
    title: 'phosphor-solid',
    description:
      'Phosphor is a flexible icon family for interfaces, diagrams, presentations — whatever, really.',
    keywords: ['phosphor', 'ui', 'icon'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
  }),
  packageBy('Matteo Bruni', {
    link: 'https://github.com/tsparticles/solid',
    title: '@tsparticles/solid',
    description: 'Official tsParticles implementation for Solid.',
    keywords: ['particles', 'confetti', 'ui'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
  }),
  packageBy('Moshe Uminer', {
    link: 'https://github.com/mosheduminer/solid-form-action',
    title: 'solid-form-action',
    description:
      'This package provides a function that accepts a definition of the initial state of your form, its validation, and submission.',
    keywords: ['action', 'form', 'validation', 'ui'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Robert Soriano', {
    link: 'https://github.com/wobsoriano/vite-solid-tailwind-starter',
    title: 'vite-solid-tailwind-starter',
    description: 'Starter using Vite + Solid + Tailwind CSS.',
    keywords: ['starter', 'templates', 'vite', 'tailwind'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
  }),
  packageBy('Ari Seyhun', {
    link: 'https://www.npmjs.com/package/solid-urql',
    title: 'solid-urql',
    description: 'A highly customizable and versatile GraphQL client for Solid.',
    keywords: ['graphql', 'url', 'url', 'formidable'],
    official: false,
    categories: [ResourceCategory.Data],
    maintained: false,
  }),
  packageBy('Pablo Berganza', {
    link: 'https://github.com/pablo-abc/solid-reach',
    title: 'solid-reach',
    description:
      'This is a port of ReachUI for Solid that (hopefully) will serve you as The Accessible Foundation for Solid Apps and Design Systems.',
    keywords: ['accessibility', 'system', 'reach', 'ui'],
    official: false,
    categories: [ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Pablo Berganza', {
    link: 'https://github.com/pablo-abc/felte',
    title: 'Felte',
    description:
      'An extensible form library that supports Solid. No Field or Form components are needed, just plain stores and actions.',
    keywords: ['form', 'validator', 'validation', 'input'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Josh Wilson', {
    link: 'https://github.com/joshwilsonvu/eslint-plugin-solid',
    title: 'eslint-plugin-solid',
    description:
      "It is not yet stable, and some rules may change, but it's well tested and should be helpful in Solid projects today.",
    keywords: ['linter', 'eslint', 'plugin'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.BuildUtilities],
  }),
  packageBy('Alexandre Mouton Brady', {
    link: 'https://github.com/amoutonbrady/solid-i18n',
    title: '@amoutonbrady/solid-i18n',
    description: 'Tiny translation library for solid-js inspired by rosetta.',
    keywords: [
      'i18n',
      'localisation',
      'localization',
      'translate',
      'translations',
      'language',
      'rosetta',
    ],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.Data],
    maintained: false,
  }),
  packageBy('David Di Biase', {
    link: 'https://github.com/davedbase/solid-slider',
    title: 'solid-slider',
    description: 'A carousel/slider implementation in TypeScript for Solid using KeenSlider.',
    keywords: [
      'slider',
      'carouse',
      'solid',
      'keen',
      'slider',
      'carousel',
      'caroussel',
      'slideshow',
      'gallery',
      'plugin',
    ],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Justinas Delinda', {
    link: 'https://github.com/minht11/solid-virtual-container',
    title: 'solid-virtual-container',
    description: 'Efficient, single direction virtual list/grid for Solid-js.',
    keywords: ['container', 'virtual', 'list', 'grid'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Alexey Kryazhev', {
    link: 'https://github.com/uNmAnNeR/imaskjs/tree/master/packages/solid-imask',
    title: 'solid-imask',
    description: 'Official Solid.js implementation for imaskjs.',
    keywords: ['input', 'mask', 'form', 'ui'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Robert Soriano', {
    link: 'https://github.com/wobsoriano/solid-zustand/',
    title: 'solid-zustand',
    description: 'Zustand state management for Solid.',
    keywords: ['container', 'state', 'zustand'],
    official: false,
    categories: [ResourceCategory.Data],
  }),
  packageBy('Robert Soriano', {
    link: 'https://github.com/wobsoriano/solid-supabase',
    title: 'solid-supabase',
    description:
      'A simple wrapper around Supabase.js (Firebase replacement) that gives you access to the client as a Solid hook.',
    keywords: ['database', 'firebase', 'wrapper'],
    official: false,
    categories: [ResourceCategory.Data],
  }),
  packageBy('Xavier Loh', {
    link: 'https://github.com/otonashixav/solid-flip',
    title: 'solid-flip',
    description: 'A lightweight transition library for solid-js.',
    keywords: ['animation', 'transition'],
    official: false,
    categories: [ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Alexis H. Munsayac', {
    link: 'https://github.com/lxsmnsyc/solid-uppy',
    title: 'solid-uppy',
    description: 'Sleek, modular open source JavaScript file uploader for Solid using Uppy.',
    keywords: ['form', 'upload'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Alexis H. Munsayac', {
    link: 'https://github.com/LXSMNSYC/babel-plugin-solid-labels',
    title: 'babel-plugin-solid-labels',
    description: 'Compile-time reactive expressions for SolidJS.',
    keywords: ['labels', 'expessions', 'babel', ' compile-time'],
    official: false,
    categories: [ResourceCategory.BuildUtilities, ResourceCategory.Plugins],
  }),
  packageBy('Alexis H. Munsayac', {
    link: 'https://github.com/lxsmnsyc/terracotta',
    title: 'terracotta',
    description: 'Headless UI for SolidJS.',
    keywords: ['design', 'ui', 'components', 'headless'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Alexis H. Munsayac', {
    link: 'https://github.com/LXSMNSYC/solid-tiptap',
    title: 'solid-tiptap',
    description: 'Solid bindings for TipTap.',
    keywords: ['tiptap', 'ui', 'editor', 'wysiwyg'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
  }),
  packageBy('Alexis H. Munsayac', {
    link: 'https://github.com/LXSMNSYC/solid-popper',
    title: 'solid-popper',
    description: 'Solid bindings for Popper.js.',
    keywords: ['popper', 'tooltip', 'positioning'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
  }),
  packageBy('Caleb Taylor', {
    link: 'https://aquaductape.github.io/solid-dismiss/',
    title: 'solid-dismiss',
    description: 'Handle "click outside" behavior to close dropdowns/popups for Solid.',
    keywords: ['click', 'outside', 'dismiss'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
  }),
  packageBy('Wilton Silva', {
    link: 'https://github.com/niliadu/solid-js-form',
    title: 'solid-js-form',
    description: 'Form library for Solid.JS that uses yup as the validation schema.',
    keywords: ['input', 'form'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
  }),
  packageBy('Isaac Hagoel', {
    link: 'https://github.com/isaacHagoel/solid-dnd-directive',
    title: 'solid-dnd-directive',
    description:
      'A feature-complete implementation of drag and drop for Solid JS using a custom directive.',
    keywords: ['dnd', 'drag', 'drop'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1633118125000,
  }),
  packageBy('Ryan Turnquist', {
    link: 'https://github.com/rturnq/solid-auth0',
    title: 'solid-auth0',
    description: 'Auth0 integration for solid-js which wraps @auth0/auth0-spa-js.',
    keywords: ['authentication', 'auth0', 'auth'],
    official: false,
    categories: [ResourceCategory.Plugins],
    published_at: 1633118125000,
    maintained: false,
  }),
  packageBy('David Di Biase', {
    link: 'https://github.com/solidjs-community/solid-primitives',
    title: 'solid-primitives',
    description: "A library of high-quality primitives that extend Solid's reactivity.",
    keywords: ['geolocation', 'timer', 'storage', 'debounce', 'throttle', 'primitives'],
    official: false,
    categories: [ResourceCategory.Primitives],
    published_at: 1633118125000,
  }),
  packageBy('Alexis H. Munsayac', {
    link: 'https://github.com/lxsmnsyc/solid-giphy',
    title: 'solid-giphy',
    description: 'Solid bindings for Giphy API service.',
    keywords: ['giphy', 'images'],
    official: false,
    categories: [ResourceCategory.UI],
    published_at: 1634917094000,
  }),
  packageBy('Aftab Alam', {
    link: 'https://github.com/one-aalam/solid-starter-kit',
    title: 'solid-starter-kit',
    description:
      'Solid Starter Kit is an opinionated boilerplate with Supabase, Tailwind, TS and Prettier.',
    keywords: ['supabase', 'tailwind', 'tailwind'],
    official: false,
    categories: [ResourceCategory.Starters],
    published_at: 1634917094000,
    maintained: false,
  }),
  packageBy('Andi Rosca', {
    link: 'https://github.com/andi23rosca/tiptap-solid',
    title: 'tiptap-solid',
    description: 'Solid components for tiptap v2.',
    keywords: ['tiptap', 'ui', 'editor', 'wysiwyg'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1634917094000,
  }),
  packageBy('swise0', {
    link: 'https://github.com/swise0/solid-toast-notify',
    title: 'solid-toast-notify',
    description: 'Toast notify element.',
    keywords: ['notify', 'toast'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1634672820000,
  }),
  packageBy('Andi Rosca', {
    link: 'https://github.com/andi23rosca/solid-markdown',
    title: 'solid-markdown',
    description: 'Ported version of react-markdown for Solid markdown generation.',
    keywords: ['markdown', 'react-markdown', 'parser'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1633895338000,
  }),
  packageBy('Reinaldy Rafli', {
    link: 'https://github.com/aldy505/vite-plugin-pages-solid',
    title: 'vite-plugin-pages-solid',
    description: 'A fork of vite-plugin-pages for Vue adapted for Solid.',
    keywords: ['vite', 'pages', 'build'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
    published_at: 1634931664000,
    maintained: false,
  }),
  packageBy('Alex Lohr', {
    link: 'https://github.com/atk/solid-register',
    title: 'solid-register',
    description: 'Allows running and testing Solid.js browser code in Node.js.',
    keywords: ['runner', 'testing'],
    official: false,
    categories: [ResourceCategory.Testing],
    published_at: 1635095541000,
  }),
  packageBy('Microsoft', {
    link: 'https://github.com/microsoft/playwright',
    title: '@playwright/experimental-ct-solid',
    description:
      'Fast and reliable component testing in a real browser simular to solid-testing-library',
    keywords: ['runner', 'testing'],
    official: false,
    categories: [ResourceCategory.Testing],
    published_at: 1669633548145,
  }),
  packageBy('merged-js', {
    link: 'https://github.com/merged-js/solid-apollo',
    title: 'solid-apollo',
    description: 'An Apollo client for Solid.',
    keywords: ['apollo', 'graphql'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.Data],
    published_at: 1635523744000,
  }),
  packageBy('merged-js', {
    link: 'https://github.com/merged-js/react-solid',
    title: 'react-solid',
    description: 'A way to use Solid components inside React.',
    keywords: ['react', 'binding'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.Data],
    published_at: 1635523744000,
    maintained: false,
  }),
  packageBy('Inlang', {
    link: 'https://inlang.com/c/solid',
    title: 'ParaglideJS',
    description:
      'An ultra-efficient i18n library that scales to zero. Comes with first class integration with SolidStart',
    keywords: [
      'i18n',
      'localisation',
      'localization',
      'translate',
      'translations',
      'language',
      'intl',
    ],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI, ResourceCategory.Data],
    published_at: 1702989010000,
    maintained: false,
  }),
  packageBy('Sanich Kotikov', {
    link: 'https://github.com/SanichKotikov/solid-i18n',
    title: 'solid-i18n',
    description: 'Tiny translation library for solid-js inspired by Rosetta.',
    keywords: [
      'i18n',
      'localisation',
      'localization',
      'translate',
      'translations',
      'language',
      'rosetta',
    ],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1635697432000,
  }),
  packageBy('Sagar Poudel', {
    link: 'https://github.com/poudels14/slate-solid',
    title: 'slate-solid',
    description: 'Slate Solid is a solid-js wrapper for Slate rich text editor.',
    keywords: ['slate', 'wysiwyg', 'editor', 'rich text'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1635697432000,
    maintained: false,
  }),
  packageBy('Brendan-csel', {
    link: 'https://solid-libs.github.io/solid-bootstrap/#/',
    title: 'solid-bootstrap',
    description: 'The most popular front-end framework rebuilt for SolidJS.',
    keywords: ['bootstrap', 'design', 'ui', 'components'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1638514856000,
  }),
  packageBy('Oren Elbaum', {
    link: 'https://github.com/orenelbaum/babel-plugin-solid-undestructure',
    title: 'babel-plugin-solid-undestructure',
    description:
      'This babel plugin allows you to destructure your props in your Solid components without losing reactivity.',
    keywords: ['spread', 'props', 'babel', 'plugin'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.BuildUtilities],
    published_at: 1638514856000,
  }),
  packageBy('Prince Neil Cedrick Castro', {
    link: 'https://github.com/git-ced/solid-plyr',
    title: 'solid-plyr',
    description: 'A simple HTML5, YouTube and Vimeo player (Plyr) for SolidJS.',
    keywords: ['player', 'video', 'html5', 'youtube', 'vimeo'],
    official: false,
    categories: [ResourceCategory.Plugins],
    published_at: 1638915904000,
    maintained: false,
  }),
  packageBy('Amin Yahyaabadi', {
    link: 'https://github.com/aminya/solid-simple-table',
    title: 'solid-simple-table',
    description:
      'Solid SimpleTable is a blazing fast reactive table component that gives you freedom.',
    keywords: ['table', 'simple'],
    official: false,
    categories: [ResourceCategory.UI],
    published_at: 1639091168000,
    maintained: false,
  }),
  packageBy('John Carroll', {
    link: 'https://gitlab.com/john.carroll.p/rx-controls',
    title: 'rx-controls-solid',
    description:
      'RxControls provides several javascript FormControl objects to make dealing with forms easier.',
    keywords: ['forms', 'rx'],
    official: false,
    categories: [ResourceCategory.UI],
    published_at: 1640895137000,
    maintained: false,
  }),
  packageBy('high1', {
    link: 'https://github.com/high1/solid-social#readme',
    title: 'solid-social',
    description:
      'Social components for solid-js. These components are a port of MDX Embed, but can be used in other contexts, hence solid-social.',
    keywords: [
      'twitter',
      'twitch',
      'youtube',
      'social',
      'social media',
      'soundcloud',
      'codepen',
      'flickr',
      'gifma',
      'vimeo',
    ],
    official: false,
    categories: [ResourceCategory.UI],
    published_at: 1640995937000,
  }),
  packageBy('high1', {
    link: 'https://github.com/high1/solid-jsx',
    title: 'solid-jsx',
    description:
      'Use Solid components with MDX. Enabled Vite and Rollup in general to parse MDX components into Solid.',
    keywords: ['mdx'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
    published_at: 1640995937000,
  }),
  packageBy('Jack Herrington', {
    link: 'https://github.com/jherr/chrome-extension-boilerplate-solid',
    title: 'chrome-extension-boilerplate-solid',
    description: 'Chrome Extensions boilerplate with SolidJS',
    keywords: ['chrome', 'extension', 'plugin'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
    published_at: 1641869878000,
    maintained: false,
  }),
  packageBy('Alexis H. Munsayac', {
    link: 'https://github.com/LXSMNSYC/solid-marked',
    title: 'solid-marked',
    description: 'MDX/Markdown compiler for SolidJS including GitHub-flavored markdown',
    keywords: ['mdx', 'marked', 'markdown', 'mdast'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
    published_at: 1642189449000,
  }),
  {
    link: 'https://github.com/thisbeyond/solid-select',
    title: 'solid-select',
    description: 'A Select component for Solid.',
    author: 'thisbeyond',
    author_url: 'https://github.com/thisbeyond',
    keywords: ['select', 'dropdown', 'component', 'ui'],
    official: false,
    type: PackageType.Package,
    categories: [ResourceCategory.UI],
    published_at: 1644103436000,
  },
  packageBy('Oren Elbaum', {
    link: 'https://github.com/orenelbaum/babel-plugin-reactivars-solid',
    title: 'babel-plugin-reactivars-solid',
    description:
      'A Babel plugin that lets you use a Svelte like syntax with Solid (a React version is a WIP).',
    keywords: ['svelte', 'reactive', 'vars'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
    published_at: 1644609963000,
    maintained: false,
  }),
  packageBy('Erik Demaine', {
    link: 'https://github.com/edemaine/meteor-solid',
    title: 'meteor-solid',
    description: 'A Meteor plugin for the Solid JSX compiler.',
    keywords: ['meteor'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
    published_at: 1644771355777,
    maintained: false,
  }),
  packageBy('Erik Demaine', {
    link: 'https://github.com/edemaine/solid-meteor-data',
    title: 'solid-meteor-data',
    description:
      'Integration between Solid and Meteor reactivity, including helpers for managing Meteor data in Solid components.',
    keywords: ['meteor'],
    official: false,
    categories: [ResourceCategory.Data],
    published_at: 1644771355777,
    maintained: false,
  }),
  packageBy('Robert Soriano', {
    link: 'https://github.com/wobsoriano/solid-firebase',
    title: 'solid-firebase',
    description: 'A range of useful Solid hooks for Firebase.',
    keywords: ['firebase', 'database', 'hooks'],
    official: false,
    categories: [ResourceCategory.Data],
    published_at: 1644771355777,
  }),
  packageBy('Neil Chudleigh', {
    link: 'https://github.com/nchudleigh/solid-virtual-list',
    title: 'solid-virtual-list',
    description:
      "Given a list of items, only render what's visible on the screen while allowing scrolling the whole list.",
    keywords: ['scroll', 'visibility', 'virtual', 'windowed', 'list'],
    official: false,
    categories: [ResourceCategory.Data],
    published_at: 1676773128677,
  }),
  packageBy('Tanvesh Sarve', {
    link: 'https://github.com/tanvesh01/motion-signals',
    title: 'motion-signals',
    description:
      'A wrapper over Motion One, An animation library, built on the Web Animations API for the smallest filesize and the fastest performance.',
    keywords: ['motionone', 'motion', 'animation', 'windowed'],
    official: false,
    categories: [ResourceCategory.UI],
    published_at: 1646088393000,
    maintained: false,
  }),
  packageBy('Fabien Marie-Louise', {
    link: 'https://hope-ui.com/',
    title: 'hope-ui',
    description: "The SolidJS component library you've hoped for.",
    keywords: ['hope', 'chakra', 'design', 'ui', 'components'],
    official: false,
    maintained: false,
    categories: [ResourceCategory.UI],
    published_at: 1647104517182,
  }),
  packageBy('Ionic Team', {
    link: 'https://github.com/ionic-team/capacitor-solidjs-templates',
    title: 'capacitor-solidjs-templates',
    description:
      'This repository holds production ready Capacitor templates for building native mobile applications using SolidJS + vite.',
    keywords: ['capacitor', 'ionic', 'vite'],
    official: false,
    categories: [ResourceCategory.UI],
    published_at: 1647496275000,
    maintained: false,
  }),
  packageBy('DigiChanges', {
    link: 'https://github.com/DigiChanges/solid-multiselect',
    title: 'solid-multiselect',
    description: 'A multi-select dropdown implementation for SolidJS.',
    keywords: ['component', 'multiselect', 'ui', 'dropdown', 'searchable'],
    official: false,
    categories: [ResourceCategory.UI],
    published_at: 1642085029000,
  }),
  packageBy('Juanra GM', {
    link: 'https://suid.io',
    title: 'SUID - Material UI',
    description: 'A port of MUI built with SolidJS.',
    keywords: ['components', 'material', 'mui', 'styled-component', 'icons', 'ui', 'design'],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.AddOn],
    published_at: 1648751735000,
  }),
  packageBy('Jao Austero', {
    link: 'https://github.com/jaoaustero/solid-tawk-messenger',
    title: 'Tawk.to Messenger',
    description: 'Tawk messenger chat for SolidJS',
    keywords: [
      'tawk',
      'tawkto',
      'live-chat',
      'chat-plugin',
      'chat-widget',
      'kb',
      'knowledge-base',
      'message',
    ],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.AddOn],
    published_at: 1651083453000,
  }),
  packageBy('Erik C. Forés', {
    link: 'https://github.com/StudioLambda/TurboSolid',
    title: 'TurboSolid',
    description: 'Lightweight asynchronous data management for solid.',
    keywords: ['cache', 'turbo', 'data', 'async', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.Data],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Mohammad Bagher Abiyat', {
    link: 'https://github.com/Aslemammad/solid-spring',
    title: 'solid-spring',
    description:
      'solid-spring is a spring-physics first animation library for SolidJS based on react-spring/core.',
    keywords: ['spring', 'animation', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('François Wouts', {
    link: 'https://github.com/fwouts/previewjs',
    title: 'previewjs',
    description: 'Preview.js lets you preview Solid components instantly in your IDE.',
    keywords: ['preview', 'components', 'previewjs', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
  }),
  packageBy('specialdoom', {
    link: 'https://github.com/specialdoom/solid-rev-kit',
    title: 'RevKit UI for SolidJS',
    description: 'Design System UI Kit for busy designers',
    keywords: ['components', 'ui', 'revkit'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Joe Pea', {
    link: 'https://github.com/lume/classy-solid',
    title: 'classy-solid',
    description:
      'Tools for class-based reactivity powered by Solid.js, and for using classes as Solid components (f.e. in a JSX template).',
    keywords: ['class', 'classes', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.Data],
    published_at: 1651891327000,
  }),
  packageBy('CompendiumDevTools', {
    link: 'https://github.com/CompendiumDevTools/library',
    title: 'CompendiumDevTools',
    description:
      'A library for connecting frameworks and state management libraries to Compendium DevTools.',
    keywords: ['devtools', 'compendium'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.Data],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Ignatius Aditya Setyadi', {
    link: 'https://github.com/AdityaSetyadi/form-gear',
    title: 'form-gear',
    description:
      'FormGear is a framework engine for dynamic form creation and complex form processing and validation for data collection.',
    keywords: ['form', 'formgear', 'gear', 'solidhack', 'survey', 'data-collection'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('gstatem', {
    link: 'https://github.com/gstatem/gstatem',
    title: 'GStatem',
    description: 'GStatem is a small, simple and fast state-management tool.',
    keywords: ['state', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.Data],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Lily Black', {
    link: 'https://github.com/L1lith/Melon-Solid',
    title: 'melon-solid',
    description:
      'This project fuses the awesome frameworks Melon.js (for game development) and Solid.js.',
    keywords: ['game', 'engine', 'melon', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Kajetan Świątek', {
    link: 'https://github.com/kajetansw/solar-forms',
    title: 'solar-forms',
    description: "Form library for SolidJS inspired by Angular's reactive forms.",
    keywords: ['solar', 'forms', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1648998307145,
    maintained: false,
  }),
  packageBy('Travis Waith-Mair', {
    link: 'https://github.com/Bedrock-Layouts/Solid-Bedrock',
    title: 'solid-bedrock',
    description: 'The Lodash of Web Layouts, a collection of utility components.',
    keywords: ['bedrock', 'components', 'layout', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Erik Verweij', {
    link: 'https://github.com/everweij/solid-boundaries',
    title: 'solid-boundaries',
    description: 'A utility to track the bounds of html-elements in SolidJS.',
    keywords: ['boundaries', 'elements', 'html', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Yonatan Bendahan', {
    link: 'https://github.com/yonathan06/solid-cached-resource',
    title: 'solid-cached-resource',
    description: 'Create a solid resource attached to a cached state by a unique key.',
    keywords: ['cache', 'resources', 'createsResource', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.Data],
    published_at: 1651891327000,
  }),
  packageBy('Aditya Agarwal', {
    link: 'https://github.com/itaditya/solid-command-palette',
    title: 'solid-command-palette',
    description: 'Add a command palette to your Solid.js app.',
    keywords: ['command', 'palette', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Kai Huebner', {
    link: 'https://github.com/GIShub4/solid-map-gl',
    title: 'solid-map-gl',
    description: 'Solid Component Library for Mapbox GL JS.',
    keywords: ['mapbox', 'webgl', 'geography', 'map', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
  }),
  packageBy('T6', {
    link: 'https://github.com/tjjfvi/solid-native',
    title: 'solid-native',
    description:
      'Solid Native expands the Solid ecosystem to include development of native mobile applications.',
    keywords: ['native', 'applications', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Maciej Kwaśniak', {
    link: 'https://github.com/Exelord/solid-proxies',
    title: 'solid-proxies',
    description: "This package provides signaled versions of Javascript's built-in objects.",
    keywords: ['primitives', 'proxies', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.Data],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Maciej Kwaśniak', {
    link: 'https://github.com/Exelord/solid-services',
    title: 'solid-services',
    description:
      'Services are "global" objects useful for features that require shared state or persistent connections.',
    keywords: ['service', 'angular', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.Data],
    published_at: 1651891327000,
  }),
  packageBy('Cain Atkinson', {
    link: 'https://github.com/yellowsink/solid-reactor',
    title: 'solid-reactor',
    description: 'A compiler to ease the move from React to SolidJS.',
    keywords: ['react', 'solid', 'compiler', 'codemod', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.BuildUtilities],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Paul Heggeseth', {
    link: 'https://github.com/pheggeseth/solid-ui',
    title: 'solid-ui',
    description:
      'Reactive primitives and hooks for building declarative, accessible, composable UI components with SolidJS.',
    keywords: ['components', 'ui', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.Data],
    published_at: 1651891327000,
  }),
  packageBy('Tiago Cavalcante', {
    link: 'https://github.com/TiagoCavalcante/solidjs-div-100vh',
    title: 'solidjs-div-100vh',
    description:
      'This is a workaround for iOS Safari and other mobile browsers forked from react-div-100vh by mvasin.',
    keywords: ['react-div-100vh', 'safari', 'height', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
    maintained: false,
  }),
  packageBy('Hervé Verdavaine', {
    link: 'https://github.com/verdavaine/solidgraph',
    title: 'SolidGraph',
    description: 'SolidGraph lets you build applications with SolidJs and WunderGraph.',
    keywords: ['wundergraph', 'graph', 'visual', 'solidhack'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1651891327000,
    maintained: false,
  }),
  {
    link: 'https://github.com/solidjs-community/solid-motionone',
    title: '@motionone/solid',
    description: 'Offical Motion One library for hardware accelerated animations in Solid.',
    author: 'davedbase & thetarnav',
    author_url: 'https://motion.dev/',
    keywords: ['motionone', 'motion', 'animation', 'official'],
    official: false,
    type: PackageType.Package,
    categories: [ResourceCategory.UI],
    published_at: 1652052027000,
  },
  packageBy('Mikkel Ringaud', {
    link: 'https://github.com/Vexcited/solid-hcaptcha',
    title: 'solid-hcaptcha',
    description: 'hCaptcha Component Library for Solid.',
    keywords: ['hcaptcha', 'captcha'],
    official: false,
    categories: [ResourceCategory.Plugins],
  }),
  packageBy('Jacob Kofron', {
    link: 'https://github.com/gnomical/solid-theme-provider',
    title: 'solid-theme-provider',
    description:
      'Lightweight, customizable theme switcher that injects css variables into the :root style element.',
    keywords: ['themes', 'dark-mode', 'css', 'prefers-color-scheme'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Aryan Deora', {
    link: 'https://github.com/ardeora/solid-toast',
    title: 'solid-toast',
    description: 'Customizable Toast Notifications for SolidJS',
    keywords: ['toast', 'notifications', 'snackbar'],
    official: false,
    categories: [ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Eugene Matsumura', {
    link: 'https://github.com/SushiWaUmai/pyscript-solid',
    title: 'pyscript-solid',
    description: 'Write python code in Solid.js using Pyscript.',
    keywords: ['pyscript', 'python', 'wrapper'],
    official: false,
    categories: [ResourceCategory.Plugins],
    maintained: false,
  }),
  packageBy('Dirag Biswas', {
    link: 'https://github.com/diragb/solid-custom-scrollbars',
    title: 'solid-custom-scrollbars',
    description: 'Custom Scrollbars for Solid.',
    keywords: ['scrollbars', 'scrolling', 'ui'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
  }),
  packageBy('Daniel Still', {
    link: 'https://github.com/StillScripts/solid-typer',
    title: 'solid-typer',
    description: 'Add text-typing animations to Solid.',
    keywords: ['typing', 'typer', 'typewriter', 'animation', 'text'],
    official: false,
    categories: [ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Fastify', {
    link: 'https://github.com/fastify/fastify-dx/tree/main/packages/fastify-dx-solid',
    title: 'fastify-dx-solid',
    description: 'Fastify DX for Solid is a renderer adapter for fastify-vite.',
    keywords: ['full stack', 'fastify', 'framework', 'server', 'back-end'],
    official: false,
    categories: [ResourceCategory.UI],
    maintained: false,
  }),
  {
    link: 'https://github.com/tahti-studio/solid-knobs',
    title: 'solid-knobs',
    description: 'Primitives for building user-friendly parameter controls.',
    author: 'maxjvh',
    author_url: 'https://github.com/maxjvh',
    keywords: ['control', 'slider', 'knob', 'audio'],
    official: false,
    type: PackageType.Package,
    categories: [ResourceCategory.UI],
    maintained: false,
  },
  packageBy('Swiper', {
    link: 'https://swiperjs.com/solid',
    title: 'swiper/solid',
    description: 'The most modern mobile touch slider for Solid.',
    keywords: ['swiper', 'slider', 'slide', 'ui', 'carousel'],
    official: false,
    categories: [ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Martijn Faassen', {
    link: 'https://github.com/faassen/solid-dexie',
    title: 'solid-dexie',
    description: 'Integrates Dexie queries with Solid.',
    keywords: ['IndexedDB', 'dexie', 'storage', 'query', 'database'],
    official: false,
    categories: [ResourceCategory.Data],
    maintained: false,
  }),
  packageBy('David Di Biase', {
    link: 'https://github.com/davedbase/solid-confetti-explosion',
    title: 'solid-confetti-explosion',
    description: 'Get the party started with Solid! A confetti Component.',
    keywords: ['confetti', 'explode'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Dirag Biswas', {
    link: 'https://github.com/diragb/solid-custom-navigation',
    title: 'solid-custom-navigation',
    description:
      'Custom navigations for Solid, written in Typescript. Implement custom page transition logic and ✨ animations ✨.',
    keywords: ['navigation', 'animation', 'custom navigation', 'ui', 'typescript'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Dirag Biswas', {
    link: 'https://github.com/diragb/solid-outside-click-handler',
    title: 'solid-outside-click-handler',
    description: 'Detect and handle clicks outside a Solid component.',
    keywords: ['detect', 'outside', 'click', 'ui', 'typescript'],
    official: false,
    categories: [ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Dirag Biswas', {
    link: 'https://github.com/diragb/solid-copy-to-clipboard',
    title: 'solid-copy-to-clipboard',
    description: 'Copy to clipboard for Solid with custom event triggers.',
    keywords: ['copy', 'to', 'clipboard', 'ui', 'typescript'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Robert Soriano', {
    link: 'https://github.com/wobsoriano/solid-apexcharts',
    title: 'solid-apexcharts',
    description: 'Build interactive visualizations in Solid. Powered by ApexCharts.',
    keywords: ['charts', 'apex', 'ui'],
    official: false,
    categories: [ResourceCategory.DataVisualization],
  }),
  {
    link: 'https://www.locatorjs.com/install/solidjs',
    title: 'LocateJS',
    description:
      'A React, Preact and Solid-supported dev tool that lets you click on any component in the browser to open its code in your IDE..',
    author: 'LocateJS',
    author_url: '',
    keywords: ['devtool', 'developer tool', 'locate'],
    official: false,
    type: PackageType.Package,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI, ResourceCategory.Plugins],
  },
  packageBy('Karthikeyan Ranasthala', {
    link: 'https://github.com/KarthikeyanRanasthala/solid-bottomsheet',
    title: 'solid-bottomsheet',
    description: 'A light-weight Bottomsheet UI component for Solid JS with zero dependencies.',
    keywords: ['bottomsheet', 'drawer', 'ui'],
    official: false,
    categories: [ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Simone Mastromattei', {
    link: 'https://github.com/smastrom/solid-collapse',
    title: 'solid-collapse',
    description: 'Tiny and performant collapse component for SolidJS.',
    keywords: ['collapse', 'accordion', 'ui'],
    official: false,
    categories: [ResourceCategory.UI],
    maintained: false,
  }),
  packageBy('Olivier Gamache', {
    link: 'https://github.com/olgam4/bat',
    title: 'bat',
    description: 'Opinionated Vite Starter Template',
    keywords: ['starter', 'typescript', 'vite', 'tailwind', 'vitesse', 'pwa'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
  }),
  packageBy('Nikhil Saraf', {
    link: 'https://www.npmjs.com/package/solid-mdx/v/0.0.6',
    title: 'solid-mdx',
    description: 'Easily use Markdown files for content and documentation in your solid-js apps.',
    keywords: ['mdx', 'plugin'],
    official: false,
    categories: [ResourceCategory.BuildUtilities],
  }),
  packageBy('Tanstack', {
    link: 'https://tanstack.com/query/v4/docs/adapters/solid-query',
    title: '@tanstack/solid-query',
    description: 'Provides a 1st-class API for using TanStack Query with SolidJS.',
    keywords: ['tanstack', 'query'],
    official: false,
    categories: [ResourceCategory.Data],
  }),
  libraryBy('Gabriel Pureliani', {
    link: 'https://github.com/pureliani/solid-query',
    title: '@gapu/solid-query',
    description: 'Primitives for managing queries and cache in solid.js',
    keywords: ['api', 'query', 'solid-query'],
    official: false,
    categories: [ResourceCategory.Data, ResourceCategory.Primitives],
  }),
  packageBy('Tanstack', {
    link: 'https://tanstack.com/virtual/v3/docs/adapters/solid-virtual',
    title: '@tanstack/solid-virtual',
    description: 'Headless UI for Virtualizing Large Element Lists',
    keywords: ['tanstack', 'query'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Tanstack', {
    link: 'https://tanstack.com/table/v8/docs/adapters/solid-table',
    title: '@tanstack/solid-table',
    description: 'Headless UI for building powerful tables & datagrids',
    keywords: ['tanstack', 'table'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  {
    link: 'https://ag-grid.com/react-data-grid/solidjs/',
    title: 'ag-grid-solid',
    description:
      "All of the grid's core rendering (headers, rows, cells etc) is rendered using Solid.",
    author: 'AG Grid',
    author_url: 'https://ag-grid.com/',
    keywords: ['grid', 'ag grid', 'ag-grid'],
    official: false,
    type: PackageType.Package,
    categories: [ResourceCategory.DataVisualization, ResourceCategory.UI],
  },
  {
    link: 'https://github.com/Supertigerr/solid-named-router',
    title: 'Solid Named Router',
    description: 'Easy to use named router for solid-js. Inspired by Vue Router.',
    author: 'Supertiger',
    author_url: 'https://github.com/Supertigerr',
    keywords: ['named', 'router'],
    official: false,
    type: PackageType.Package,
    categories: [ResourceCategory.Routers],
    maintained: false,
  },
  packageBy('Miguel Vieira', {
    link: 'https://github.com/miguelsalesvieira/solid-flow',
    title: 'solid-flow',
    description: 'A simple component for building interactive node-based diagrams and editors.',
    keywords: ['ui', 'drag', 'flow'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Mauricio Rivera', {
    link: 'https://github.com/webblocksapp/solid-form-handler',
    title: 'solid-form-handler',
    description:
      'SolidJS library for building form components and validating forms with them. It can be integrated with vanilla form components or any SolidJS UI library.',
    keywords: ['forms', 'validations', 'form components', 'handler'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    published_at: 1664413200000,
  }),
  packageBy('Chris Czopp', {
    link: 'https://github.com/chris-czopp/solid-test-recorder',
    title: 'solid-test-recorder',
    description: 'Chrome extension to generate UI unit/integration tests.',
    keywords: [
      'testing',
      'unit',
      'integration',
      'mock',
      'vitest',
      'chrome',
      'extension',
      'automation',
    ],
    official: false,
    categories: [ResourceCategory.AddOn],
    maintained: false,
  }),
  {
    link: 'https://papanasi.js.org/',
    title: 'Papanasi: The Universal UI Library',
    description:
      'Papanasi (pronunced pɑpənæʃ or papanash) is a UI library to use cross Frameworks.',
    author: 'Quique Fdez Guerra',
    author_url: '',
    keywords: ['ui', 'components', 'universal'],
    official: false,
    type: PackageType.Package,
    categories: [ResourceCategory.UI],
  },
  libraryBy('William Berglund', {
    title: 'solid-formlet',
    description: 'Functional combinators for building reactive forms with SolidJS',
    link: 'https://github.com/functorism/solid-formlet',
    keywords: ['form', 'combinators'],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
    published_at: 1665676502786,
  }),
  packageBy('Raqueebuddin Aziz', {
    link: 'https://github.com/vanillacode314/solid-start-trpc-turborepo',
    title: 'solid-start-trpc-turborepo',
    description: 'Solid Start tRPC turborepo starter template',
    keywords: ['solid-start', 'trpc', 'turborepo', 'monorepo'],
    official: false,
    categories: [ResourceCategory.Starters],
  }),
  libraryBy('Fabian Hiller', {
    title: 'Modular Forms',
    link: 'https://modularforms.dev/',
    description:
      'Modular Forms is a JavaScript library that is build on top of SolidJS to validate and handle various types of forms. It is fast by default and the bundle size is small due to a modular design.',
    categories: [ResourceCategory.UI, ResourceCategory.Primitives, ResourceCategory.Data],
    official: false,
    keywords: ['form', 'field', 'validation', 'input', 'ui'],
    published_at: 1666197287705,
  }),
  libraryBy('Gabriel Pureliani', {
    title: '@gapu/formix',
    link: 'https://github.com/pureliani/formix',
    description:
      '@gapu/formix is a powerful form management library for SolidJS. It provides a simple and flexible API for handling complex form state, validation, and submission.',
    categories: [ResourceCategory.UI, ResourceCategory.Primitives, ResourceCategory.Data],
    official: false,
    keywords: ['form', 'field', 'validation', 'input', 'ui'],
  }),
  packageBy('Kevin Chen', {
    title: 'vite-plugin-solid-markdown',
    link: 'https://github.com/xbmlz/vite-plugin-solid-markdown',
    description: 'Compile Markdown to Solid component.',
    categories: [ResourceCategory.BuildUtilities, ResourceCategory.Plugins, ResourceCategory.UI],
    official: false,
    keywords: ['markdown', 'vite', 'plugin', 'mdx', 'solid-markdown'],
    published_at: 1671096940743,
    maintained: false,
  }),
  packageBy('Kevin Chen', {
    title: 'vitesse-solid',
    link: 'https://github.com/xbmlz/vitesse-solid',
    description:
      'Vitesse Solid is a template for building Solid apps with Vite. includes TypeScript, ESLint, Prettier, I18n, Markdown, UnoCSS, HopeUI and more.',
    categories: [ResourceCategory.Starters, ResourceCategory.UI, ResourceCategory.BuildUtilities],
    official: false,
    keywords: [
      'starter',
      'vite',
      'template',
      'boilerplate',
      'typescript',
      'eslint',
      'prettier',
      'unocss',
      'i18n',
      'darkmode',
      'pwa',
    ],
    published_at: 1671097420678,
  }),
  libraryBy('Eric Fennis', {
    title: 'lucide-solid',
    link: 'https://lucide.dev/',
    description:
      'Beautiful & consistent icon toolkit made by the community. Open-source project and a fork of Feather Icons.',
    categories: [ResourceCategory.UI, ResourceCategory.Primitives, ResourceCategory.Data],
    official: false,
    keywords: ['components', 'lucide', 'icons', 'ui', 'design', 'svg', 'feather-icons'],
    published_at: 1640969643000,
  }),
  packageBy('Fabien Marie-Louise', {
    link: 'https://kobalte.dev/',
    title: 'kobalte',
    description:
      'A library of unstyled components for building accessible web apps and design systems with SolidJS.',
    keywords: ['kobalte', 'headless', 'unstyled', 'aria', 'components'],
    official: false,
    categories: [ResourceCategory.UI],
    published_at: 1672867714000,
  }),
  libraryBy('flamrdevs', {
    title: '@klass/solid',
    link: 'https://github.com/flamrdevs/klass',
    description: 'A class variant utility library.',
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
    official: false,
    keywords: ['class', 'css', 'styled'],
    published_at: 1672135531594,
  }),
  packageBy('bigmistqke', {
    title: 'solid-textarea-autosize',
    link: 'https://github.com/bigmistqke/solid-textarea-autosize',
    description:
      '<textarea /> component for Solid which grows with content. A port of react-textarea-autosize.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['textarea', 'autosize', 'unstyled'],
    published_at: 1673290661528,
  }),
  libraryBy('Marcos Gonçalves', {
    title: '@cookbook/solid-intl',
    link: 'https://github.com/the-cookbook/solid-intl',
    description:
      'A universal internationalization (i18n) for Solid inspired by React Intl & FormatJS.',
    categories: [ResourceCategory.UI, ResourceCategory.BuildUtilities, ResourceCategory.Plugins],
    official: false,
    keywords: ['i18n', 'internation', 'l10n', 'localization', 'translation', 'ssr'],
    published_at: 1672790400000,
    maintained: false,
  }),
  packageBy('sect', {
    title: '@sect/solid-hiding-header',
    link: 'https://github.com/sectsect/solid-hiding-header',
    description: 'SolidJS header that disappears on scroll down and appears on scroll up.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['header', 'sticky-header', 'scroll'],
    published_at: 1673761074258,
  }),
  packageBy('Jacob Kofron', {
    link: 'https://github.com/gnomical/solid-fontawesome',
    title: 'solid-fontawesome',
    description: 'A FontAwesomeIcon svg component for the font awesome icon library.',
    keywords: ['icons', 'fontawesome', 'svg'],
    official: false,
    categories: [ResourceCategory.UI],
    published_at: 1674876065000,
  }),
  libraryBy('Carlos Paludetto', {
    title: '@solidjs-material/core',
    link: 'https://github.com/ceopaludetto/solid-material',
    description:
      'Solid-js high quality components built with tailwindcss and kobalte following material you guidelines.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['material-design', 'kobalte', 'tailwindcss', 'class-variance-authority'],
    published_at: 1676732932000,
    maintained: false,
  }),
  packageBy('Kevin Chen', {
    title: 'solid-color',
    link: 'https://github.com/xbmlz/solid-color',
    description: 'Color Pickers for Sketch, Photoshop, Chrome & more with SolidJS.',
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
    official: false,
    keywords: ['color', 'color-picker', 'color-picker-solid', 'github', 'twitter', 'chrome'],
    published_at: 1675664790423,
  }),
  libraryBy('Flowbite', {
    title: 'Flowbite SolidJS',
    link: 'https://flowbite.com/docs/getting-started/solid-js/',
    description: 'Build websites even faster with components on top of Tailwind CSS.',
    categories: [ResourceCategory.UI, ResourceCategory.Data, ResourceCategory.Plugins],
    official: false,
    keywords: ['ui', 'components', 'library', 'tailwind', 'plugin'],
    published_at: 1676570155000,
  }),
  libraryBy('Alexis H. Munsayac', {
    title: 'solid-mason',
    link: 'https://github.com/lxsmnsyc/solid-mason',
    description: 'Simple masonry layout in SolidJS.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['ui', 'masonry', 'mason', 'grid'],
    published_at: 1676732932000,
  }),
  libraryBy('OrJDev', {
    title: 'create-jd-app',
    link: 'https://github.com/OrJDev/create-jd-app',
    description:
      'Create modern Solid / SolidStart web application within seconds (tRPC, Prisma, Tailwind, Zod and Auth.js).',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['trpc', 'start', 'solid-start', 'auth.js', 'zod', 'tailwind', 'unocss'],
    published_at: 1676924456000,
  }),
  libraryBy('OrJDev', {
    title: 'solid-trpc',
    link: 'https://github.com/OrJDev/solid-trpc',
    description: 'A package that combines Solid and tRPC.',
    categories: [ResourceCategory.Data],
    official: false,
    keywords: ['trpc'],
    published_at: 1676924456000,
    maintained: false,
  }),
  libraryBy('OrJDev', {
    title: 'solid-start-trpc',
    link: 'https://github.com/OrJDev/solid-trpc',
    description: 'A package that combines SolidStart and tRPC.',
    categories: [ResourceCategory.Data],
    official: false,
    keywords: ['trpc', 'start', 'solidstart'],
    published_at: 1676924456000,
    maintained: false,
  }),
  libraryBy('nextauthjs', {
    title: 'solid-start-auth-example',
    link: 'https://github.com/nextauthjs/solid-start-auth-example',
    description: 'This is the official SolidStart Auth example for Auth.js.',
    categories: [ResourceCategory.Data],
    official: false,
    keywords: ['auth.js', 'permissions', 'auth'],
    published_at: 1676924456000,
  }),
  libraryBy('Moshe Uminer', {
    title: 'lexical-solid',
    link: 'https://github.com/mosheduminer/lexical-solid',
    description: 'An extensible text editor framework for SolidJS based on Lexical.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['text', 'text editor', 'wysiwyg', 'editor', 'rich text', 'lexical', 'tiptap'],
    published_at: 1677050359000,
  }),
  libraryBy('Wundergraph', {
    title: '@wundergraph/solid-query',
    link: 'https://github.com/wundergraph/wundergraph/tree/main/packages/solid-query',
    description: 'Brings all the good stuff from WunderGraph to the Solid.js ecosystem.',
    categories: [ResourceCategory.Data],
    official: false,
    keywords: ['wundergraph', 'data', 'tanstack', 'graph'],
    published_at: 1677094221000,
  }),
  packageBy('Joseph Cano', {
    title: 'solid-dzone',
    link: 'https://github.com/Jcanotorr06/solid-dzone',
    description: 'A simple and easy to use Dropzone primitive for SolidJS.',
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
    official: false,
    keywords: ['dropzone', 'drag', 'drag and drop', 'solid', 'solidjs'],
    published_at: 1677371956000,
  }),
  packageBy('Joseph Cano', {
    title: 'solid-marquee',
    link: 'https://github.com/Jcanotorr06/solid-marquee',
    description: 'A simple and lightweight Marquee component for SolidJS.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['marquee', 'solid', 'solidjs'],
    published_at: 1677504886000,
  }),
  packageBy('Simon Holmes', {
    title: 'solid-code-input',
    link: 'https://github.com/srsholmes/solid-code-input',
    description:
      'A small component that creates a lightweight text area component which will automatically syntax highlight the code you type in it.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['code', 'prism', 'highlight', 'highlight.js'],
    published_at: 1677656407000,
  }),
  packageBy('Chakra UI', {
    title: 'ark-ui',
    link: 'https://github.com/chakra-ui/ark',
    description:
      'Ark UI is a headless library for building reusable, scalable Design Systems that works in any framework.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['chakra', 'ark', 'components', 'zag', 'headless'],
    published_at: 1680036247000,
  }),
  packageBy('Vladislav Lipatov', {
    title: 'solid-undo-redo',
    link: 'https://github.com/elite174/solid-undo-redo',
    description: 'A list-based (O(1)) implementation of undo-redo for signals.',
    categories: [ResourceCategory.Primitives],
    official: false,
    keywords: ['undo', 'redo', 'undo-redo', 'history'],
    published_at: 1681923600000,
  }),
  libraryBy('Vladislav Lipatov', {
    title: 'solid-simple-datepicker',
    link: 'https://github.com/elite174/solid-simple-datepicker',
    description: 'A nice, customizable and simple datepicker component for every day.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['component', 'datepicker'],
    published_at: 1681750800000,
  }),
  libraryBy('Vladislav Lipatov', {
    title: 'solid-resizable-panels',
    link: 'https://github.com/elite174/solid-resizable-panels',
    description: 'The set of components for building resizable panels.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['component', 'resizable', 'panels'],
    published_at: 1681750800000,
  }),
  libraryBy('Mathieu Decaffmeyer', {
    title: 'solid-compose',
    link: 'https://github.com/mathieuprog/solid-compose',
    description: 'A set of reactive state for commonly used features in web apps.',
    categories: [ResourceCategory.Primitives],
    official: false,
    keywords: ['i18n', 'locale', 'storage', 'theme', 'viewport'],
    published_at: 1683211178000,
  }),
  libraryBy('Sukhpreet Singh', {
    title: 'solidjs-scroll-essentials',
    link: 'https://github.com/sacarvy/solidjs-scroll-essentials',
    description:
      'solidjs-scroll-essentials provides you with required scroll based primitives to control scroll behavior such as scroll lock in solidjs.',
    categories: [ResourceCategory.Primitives, ResourceCategory.UI],
    official: false,
    keywords: ['primitive', 'scroll'],
    published_at: 1683714279538,
    maintained: false,
  }),
  packageBy('Vyacheslav Azarenko', {
    link: 'https://github.com/s0ftik3/solid-chartjs',
    title: 'solid-chartjs',
    description: 'SolidJs component for Chart.js',
    keywords: ['charts', 'chartjs', 'ui'],
    official: false,
    categories: [ResourceCategory.DataVisualization],
  }),
  libraryBy('Daniel Sanchez', {
    link: 'https://github.com/thedanchez/uplot-solid',
    title: 'uplot-solid',
    description:
      'Solid component wrapper around μPlot -- a small, fast and performant 2D canvas based chart for time series, lines, areas, ohlc & bars',
    keywords: ['chart', 'plot', 'solid', 'ui', 'uplot'],
    official: false,
    categories: [ResourceCategory.DataVisualization],
  }),
  libraryBy('Matthew Ruona', {
    title: '@rnwonder/solid-date-picker',
    link: 'https://github.com/rnwonder/solid-date-picker',
    description: 'A simple and reusable Datepicker component for for web apps.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['component', 'datepicker', 'rangepicker', 'calendar', 'timepicker'],
    published_at: 1683352800000,
  }),
  libraryBy('Sergey Shishkin', {
    title: 'solid-maplibre',
    link: 'https://github.com/shishkin/solid-maplibre',
    description: 'SolidJS wrapper around MapLibre GL JS',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['map', 'maplibre', 'maplibre-gl-js', 'gis'],
    published_at: 1667602800000,
  }),
  libraryBy('Matthew Ruona', {
    title: 'solidjs-paystack',
    link: 'https://github.com/rnwonder/solidjs-paystack',
    description: 'Paystack payment gateway for SolidJS.',
    categories: [ResourceCategory.Primitives, ResourceCategory.UI],
    official: false,
    keywords: ['component', 'paystack', 'payment'],
    published_at: 1688908056276,
    maintained: false,
  }),
  libraryBy('Matthew Ruona', {
    title: 'solidjs-flutterwave',
    link: 'https://github.com/rnwonder/solidjs-flutterwave',
    description: 'Flutterwave payment gateway for SolidJS.',
    categories: [ResourceCategory.Primitives, ResourceCategory.UI],
    official: false,
    keywords: ['component', 'flutterwave', 'payment'],
    published_at: 1688926787929,
    maintained: false,
  }),
  libraryBy('DigiChanges', {
    title: 'solid-wizard',
    link: 'https://github.com/DigiChanges/solid-wizard',
    description: 'A wizard component for solid-js.',
    categories: [ResourceCategory.UI],
    official: false,
    keywords: ['component', 'wizard', 'steps', 'stepper'],
    published_at: 1660003099,
  }),
  libraryBy('Brian Whippo', {
    title: 'solid-algo-wallets',
    link: 'https://github.com/SilentRhetoric/solid-algo-wallets',
    description: 'Integrate multiple Algorand wallets with a SolidJS web application client',
    categories: [ResourceCategory.AddOn],
    official: false,
    keywords: ['algorand', 'wallet', 'web3'],
    published_at: 1694382818000,
  }),
  packageBy('Tronikelis', {
    title: 'solid-swr',
    link: 'https://github.com/Tronikelis/solid-swr',
    description: 'The beloved swr package ported over to solid',
    official: false,
    categories: [ResourceCategory.Data, ResourceCategory.Primitives],
    keywords: ['swr', 'fetch', 'request', 'cache'],
  }),
  packageBy('Nick Saunders', {
    link: 'https://css-hooks.com',
    title: '@css-hooks/solid',
    description:
      'Hooks enhance native inline styles with CSS features like pseudo-classes and media queries.',
    keywords: ['css', 'style', 'tailwind'],
    official: false,
    categories: [ResourceCategory.AddOn],
  }),
  packageBy('Aleksandr Lesnenko', {
    title: 'solid-monaco',
    link: 'https://github.com/alxnddr/solid-monaco',
    description: 'Monaco editor for Solid',
    keywords: ['monaco', 'editor', 'code editor', 'ui'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
  }),
  packageBy('Jessy', {
    link: 'https://github.com/jessyhq/solid-spotify-embed',
    title: 'solid-spotify-embed',
    description: 'A simple Solid component for embedding a Spotify song or album preview.',
    keywords: ['spotify', 'embed', 'music', 'iframe'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
  }),
  packageBy('Aleksandr Lesnenko', {
    title: 'echarts-solid',
    link: 'https://github.com/alxnddr/echarts-solid',
    description: 'ECharts components for Solid',
    keywords: ['charts', 'echarts', 'data visualization', 'ui'],
    official: false,
    categories: [ResourceCategory.DataVisualization],
  }),
  packageBy('Julian Soto', {
    title: 'solid-keep-alive',
    link: 'https://github.com/JulianSoto/solid-keep-alive',
    description: 'Keep alive components even after unmount, prevent rerendering on remount',
    keywords: ['alive', 'keep alive', 'remount', 'mount'],
    official: false,
    categories: [ResourceCategory.AddOn, ResourceCategory.Primitives],
    maintained: false,
  }),
  packageBy('Vladislav Lipatov', {
    link: 'https://github.com/elite174/solid-simple-popover',
    title: 'solid-simple-popover',
    description: 'A simple and customizable popover component for SolidJS based on floating-ui.',
    keywords: ['popover', 'floating-ui', 'component'],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
  }),
  packageBy('Jasmin', {
    link: 'https://corvu.dev/',
    title: 'corvu',
    description:
      'A collection of unstyled and accessible UI primitives that aim to be highly customizable while providing a delightful developer experience.',
    keywords: ['unstyled', 'headless', 'accessible', 'customizable', 'primitives', 'components'],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
  }),
  packageBy('Jasmin', {
    link: 'https://corvu.dev/docs/utilities/presence/',
    title: 'solid-presence',
    description:
      'Utility that manages the presence of an element in the DOM while being aware of pending animations.',
    keywords: ['show', 'presence', 'animation'],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
  }),
  packageBy('Jasmin', {
    link: 'https://corvu.dev/docs/utilities/focus-trap/',
    title: 'solid-focus-trap',
    description: 'Utility that traps focus inside a given DOM element.',
    keywords: ['focus', 'trap', 'keyboard', 'accessibility'],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
  }),
  packageBy('Jasmin', {
    link: 'https://corvu.dev/docs/utilities/prevent-scroll/',
    title: 'solid-prevent-scroll',
    description:
      'Utility that prevents scrolling outside of a given DOM element. Works by preventing events that else would lead to scrolling.',
    keywords: ['scroll', 'prevent', 'disable', 'remove'],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
  }),
  packageBy('Jasmin', {
    link: 'https://corvu.dev/docs/utilities/transition-size/',
    title: 'solid-transition-size',
    description:
      "Utility which makes it possible to transition the width and height of elements that don't have a fixed size applied.",
    keywords: ['transition', 'size', 'width', 'height'],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
  }),
  packageBy('Jehaad AL-Johani', {
    link: 'https://github.com/jehaad1/SolidBase',
    title: 'create-solidbase-app',
    description: 'Starter Templates CLI with Solid.js, Firebase, TailwindCSS, and Vite',
    keywords: ['template', 'starter', 'firebase', 'tailwindcss', 'tailwind', 'vite'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
  }),
  packageBy('Erik Engi', {
    link: 'https://github.com/kireerik/refo',
    title: 'refo',
    description: 'Effortless static site generation with flexibility',
    keywords: ['template', 'static', 'static-site', 'generator'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
  }),
  packageBy('PDFSlick', {
    link: 'https://github.com/pdfslick/pdfslick',
    title: '@pdfslick/solid',
    description:
      'View and Interact with PDF documents in React, SolidJS, Svelte and JavaScript apps',
    keywords: ['pdf', 'viewer'],
    official: false,
    categories: [ResourceCategory.Starters, ResourceCategory.BuildUtilities],
  }),
  packageBy('thednp', {
    link: 'https://github.com/thednp/solid-color-picker',
    title: '@thednp/solid-color-picker',
    description: 'Modern Color Picker for SolidJS',
    keywords: ['color', 'color-picker'],
    official: false,
    categories: [ResourceCategory.Plugins, ResourceCategory.UI],
  }),
  packageBy('thednp', {
    link: 'https://github.com/thednp/tinymce-solid',
    title: 'tinymce-solid',
    description: 'TinyMCE Component for SolidJS',
    keywords: ['tinymce', 'editor', 'wysiwyg'],
    official: false,
    categories: [ResourceCategory.UI],
  }),
  packageBy('Jasmin', {
    link: 'https://corvu.dev/docs/utilities/dismissible/',
    title: 'solid-dismissible',
    description:
      'Utility for creating dismissible, nestable layers. Offers different strategies to dismiss the layer, such as on outside click, escape key press, or outside focus.',
    keywords: ['dismissible', 'dismiss', 'layer', 'close', 'escape'],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
  }),
  packageBy('Jasmin', {
    link: 'https://corvu.dev/docs/utilities/list/',
    title: 'solid-list',
    description:
      'Utility to create accessible, keyboard navigable lists like search results, selects or autocompletes.',
    keywords: ['keyboard', 'accessible', 'list'],
    official: false,
    categories: [ResourceCategory.UI, ResourceCategory.Primitives],
  }),
];

export default utilities;
