import { Resource, ResourceCategory, ResourceType } from '../Resources';

const utilities: Array<Resource> = [
  {
    link: 'https://github.com/solidjs/solid-app-router',
    title: 'solid-app-router',
    description:
      "A small config-driven router inspired by Ember Router. While less dynamic than the common React it's used for things like you'd find in isomorphic metaframeworks.",
    author: 'Ryan Carniato',
    author_url: 'https://github.com/ryancarniato',
    keywords: ['router'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.Routers],
  },
  {
    link: 'https://www.npmjs.com/package/@rturnq/solid-router',
    title: 'solid-router',
    description: 'An official/unofficial router for Solid.',
    author: 'Ryan Turnquist',
    author_url: 'https://github.com/rturnq',
    keywords: ['router'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.Routers],
  },
  {
    link: 'https://github.com/mikeplus64/solid-typefu-router5',
    title: 'solid-typefu-router5',
    description:
      'This package provides a router with integration with router5 and solid-js, and features type safe router and link creation.',
    author: 'Mike Ledger',
    author_url: 'https://github.com/mikeplus64',
    keywords: ['router'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.Routers],
  },
  {
    link: 'https://github.com/solidjs/solid-meta',
    title: 'solid-meta',
    description: 'Asynchronous SSR-ready Document Head management for Solid based on React Head.',
    author: 'Ryan Carniato',
    author_url: 'https://github.com/ryancarniato',
    keywords: ['meta', 'document'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.Plugins],
  },
  {
    link: 'https://github.com/solidjs/solid-refresh',
    title: 'solid-refresh',
    description: 'This project aims to provide HMR for Solid for various bundlers.',
    author: 'Ryan Carniato',
    author_url: 'https://github.com/ryancarniato',
    keywords: ['hmr', 'refresh'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.Plugins],
  },
  {
    link: 'https://github.com/solidjs/solid-jest',
    title: 'solid-jest',
    description:
      'This library contains presets for SolidJS to easily get started testing with Jest for both browser and server rendering with Node.',
    author: 'Ryan Carniato',
    author_url: 'https://github.com/ryancarniato',
    keywords: ['testing', 'jest'],
    official: false,
    type: ResourceType.Library,
    categories: [ResourceCategory.Testing],
  },
  {
    link: 'https://github.com/solidjs/solid-testing-library',
    title: 'solid-testing-library',
    description:
      'Simple and complete Solid DOM testing utilities that encourage good testing practices.',
    author: 'Ryan Carniato',
    author_url: 'https://github.com/ryancarniato',
    keywords: ['testing'],
    official: false,
    type: ResourceType.Library,
    categories: [ResourceCategory.Testing],
  },
  {
    link: 'https://github.com/amoutonbrady/solid-heroicons',
    title: 'solid-heroicons',
    description: 'A convenient port of the Tailwind Heroicons.',
    author: 'Alexandre Mouton Brady',
    author_url: 'https://github.com/amoutonbrady',
    keywords: ['icons', 'ui', 'hero'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
  },
  {
    link: 'https://github.com/amoutonbrady/esbuild-plugin-solid',
    title: 'esbuild-plugin-solid',
    description: 'Plugin to compile solid-js jsx components with esbuild.',
    author: 'Alexandre Mouton Brady',
    author_url: 'https://github.com/amoutonbrady',
    keywords: ['esbuild', 'tooling'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.Starters],
  },
  {
    link: 'https://github.com/amoutonbrady/snowpack-solid',
    title: 'snowpack-solid',
    description:
      'Solid + snowpack + tailwindcss template You get HMR out of the box and full PWA compatible.',
    author: 'Alexandre Mouton Brady',
    author_url: 'https://github.com/amoutonbrady',
    keywords: ['snowpack', 'tooling'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.Starters],
  },
  {
    link: 'https://github.com/amoutonbrady/parcel2-solid-ts-starter',
    title: 'parcel2-solid-ts-starter',
    description:
      'This template is based on yarn 2 pnp resolution (zero-install). It also uses parcel 2 for bundling.',
    author: 'Alexandre Mouton Brady',
    author_url: 'https://github.com/amoutonbrady',
    keywords: ['parcel2', 'tooling', 'boilerplate'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.Starters],
  },
  {
    link: 'https://github.com/MrFoxPro/solid-rollup-boilerplate',
    title: 'solid-rollup-boilerplate',
    description: 'Simple starter for Rollup + Solid.',
    author: 'Dmitriy Nikiforov',
    author_url: 'https://github.com/MrFoxPro',
    keywords: ['boilerplate', 'rollup'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.Starters],
  },
  {
    link: 'https://github.com/solidjs/solid-transition-group',
    title: 'solid-transition-group',
    description:
      'Animation library influenced by React Transition Group and Vue Transitions for the SolidJS library.',
    author: 'Ryan Carniato',
    author_url: 'https://github.com/ryansolid',
    keywords: ['transitions', 'animations'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.AddOn],
  },
  {
    link: 'https://github.com/solidjs/solid-start',
    title: 'solid-start',
    description:
      'This is the home of the new official starter for Solid. This is still a work in progress.',
    author: 'Ryan Carniato',
    author_url: 'https://github.com/ryansolid',
    keywords: ['starter'],
    official: false,
    type: ResourceType.Library,
    categories: [ResourceCategory.AddOn],
  },
  {
    link: 'https://github.com/solidjs/vite-plugin-solid',
    title: 'vite-plugin-solid',
    description: 'Plugin that allows SolidJS to run with Vite.',
    author: 'Alexandre Mount Brady',
    author_url: 'https://github.com/amoutonbrady',
    keywords: ['vite', 'bundler'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.BuildUtilities, ResourceCategory.Plugins],
  },
  {
    link: 'https://github.com/thisbeyond/solid-dnd',
    title: 'solid-dnd',
    description: 'A lightweight and extremely performant drag and drop toolkit for Solid.',
    author: 'Martin Pengelly-Phillips',
    author_url: 'https://www.4degrees.pro',
    keywords: ['drag', 'drop', 'dnd'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.AddOn, ResourceCategory.Primitives],
  },
  {
    link: 'https://github.com/MrFoxPro/solid-chart.js',
    title: 'solid-chart',
    description: 'Chart.js powered by solid-js framework.',
    author: 'Dmitriy Nikiforov',
    author_url: 'https://github.com/MrFoxPro',
    keywords: ['chart', 'chart.js'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.AddOn],
  },
  {
    link: 'https://github.com/mduclehcm/solid-form',
    title: 'solid-form',
    description: 'Build 60fps forms with solid.js.',
    author: 'Le Minh Duc',
    author_url: 'https://github.com/mduclehcm',
    keywords: ['form'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.AddOn],
  },
  {
    link: 'https://github.com/storeon/solidjs',
    title: 'solid-storeon',
    description:
      'A package that helps to connect store with Solid.js to provide a better performance and developer experience while remaining so tiny.',
    author: 'Storeon',
    keywords: ['storeon', 'store'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.AddOn, ResourceCategory.Data],
  },
  {
    link: 'https://github.com/solidjs/solid-styled-components',
    title: 'solid-styled-components',
    description:
      'This library provides Styled Components and css helper found in popular JS in CSS libraries.',
    author: 'Ryan Carniato',
    author_url: 'https://github.com/ryansolid',
    keywords: ['styled', 'components', 'goober'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.AddOn],
  },
  {
    link: 'https://github.com/andgate/solid-orbit',
    title: 'solid-orbit',
    description:
      'This package provides Solid a provider and hooks for Orbit. Most notably, this provides a useQuery hook which is a query transform listener, updating component props with records as they are changed.',
    author: 'Gabriel Anderson',
    author_url: 'https://github.com/andgate',
    keywords: ['orbit', 'store', 'data'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.AddOn, ResourceCategory.Data],
  },
  {
    link: 'https://github.com/lume/lume',
    title: 'Lume',
    description:
      'A toolkit that simplifies the creation of rich and interactive 2D or 3D experiences for any device from mobile to desktop to AR/VR.',
    author: 'Joe Pea',
    author_url: 'https://github.com/trusktr',
    keywords: ['graphics', '3d', 'ui'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
  },
  {
    link: 'https://www.npmjs.com/package/phosphor-solid',
    title: 'phosphor-solid',
    description:
      'Phosphor is a flexible icon family for interfaces, diagrams, presentations — whatever, really.',
    author: 'Arturo Aguilera',
    author_url: 'https://github.com/aguilera51284',
    keywords: ['phosphor', 'ui', 'icon'],
    official: false,
    type: ResourceType.Package,
    categories: [ResourceCategory.AddOn, ResourceCategory.UI],
  },
];

export default utilities;
