import { Resource, ResourceCategory, ResourceType } from '../Resources';

const videos: Array<Resource> = [
  {
    link: 'https://www.youtube.com/watch?v=wu6HvLoi9VQ',
    title: 'How To Convert React Application To SolidJS',
    description: 'Maksim Ivanov walks us through Solid.js and how to use it.',
    author: 'Maksim Ivanov',
    author_url: 'https://www.youtube.com/user/satansdeer1',
    keywords: [''],
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1628532062000,
  },
  {
    link: 'https://www.youtube.com/watch?v=Dq5EAcup044',
    title: 'UI Libraries, Improving React.js & Music, with Ryan Carniato, Solid.js Creator',
    description: '',
    author: 'Jakub Neander',
    author_url: 'https://github.com/zaiste',
    keywords: [''],
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1616544000000,
  },
  {
    link: 'https://www.youtube.com/watch?v=P8iGK8zYzns',
    title: 'Solid.js - A Fast, Declarative, Compiled Web UI Library - Better than React.js?',
    description:
      'Zaiste Programming discusses three things that makes Solid.js and Snowpack great.',
    author: 'Jakub Neander',
    author_url: 'https://github.com/zaiste',
    keywords: [''],
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1615593600000,
  },
  {
    link: 'https://www.youtube.com/watch?v=p8e9ta269x8',
    title: 'React to Solid - Stream With Ryan Carniato',
    description:
      'Maksim Ivanov and Ryan Carniato take an existing React application and try to rewrite it using the Solid framework.',
    author: 'Maksim Ivanov',
    author_url: 'https://www.youtube.com/user/satansdeer1',
    keywords: [''],
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1617062400000,
  },
  {
    link: 'https://www.youtube.com/watch?v=-CymMzGwzP8',
    title: 'Looking at solid.js',
    description: "Looking at solid.js, a new library for reactive web UI's.",
    keywords: [''],
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1601164800000,
  },
  {
    link: 'https://www.youtube.com/watch?v=P-AGz3U8lFY',
    title: 'Learning SolidJS',
    description:
      'Alex takes a first look, building a color transformation tool and dad joke search app in the process.',
    keywords: [''],
    author: 'uidotdev',
    author_url: 'https://www.youtube.com/channel/UCbAn7pVK2VIyo-UysfWGdZQ',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1625011200000,
  },
  {
    link: 'https://www.youtube.com/watch?v=_ne2BsvFBH0',
    title: 'Solid.js - the NEXT React? In-depth code analysis.',
    description:
      "A super in-depth code conversation about the inner-workings of Solid.js from a React developer's perspective.",
    keywords: [''],
    author: 'Sawtaytoes',
    author_url: 'https://www.youtube.com/channel/UCDezHlQN79VWarlRgvmim-w',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1625184000000,
  },
  {
    link: 'https://www.youtube.com/playlist?list=PLtLhzwNMDs1fMi43erQSzXD49Y4p0TniU',
    title: 'Solid Video Series',
    description:
      'Information for developers who are interested in using the Solid JavaScript UI framework to create a web application.',
    keywords: [''],
    author: 'Eric Schmucker',
    author_url: 'https://www.youtube.com/channel/UCDezHlQN79VWarlRgvmim-w',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: undefined,
  },
  {
    link: 'https://www.youtube.com/watch?v=iyY1lT8-ZDA',
    title: 'The Deep Drive Episode #4 Reactive Frontends',
    description:
      'The Deep Dive delves into reactive front-end frameworks with Lars Gyrup, Brink Nielsen, Kos Palchyk and Ryan Carniato.',
    keywords: ['reactive', 'kos palychyk'],
    author: 'The Deep Dive',
    author_url: 'https://www.youtube.com/channel/UCsZWzmsdKz2VA49XXBK5TQA',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1615939200000,
  },
  {
    link: 'https://www.youtube.com/watch?v=OqcHoLWyyIw',
    title: 'React vs SolidJS, Fight!',
    description: "Let's compare React with the upstart newcomer Solid-JS in an eCommerce showdown!",
    keywords: ['reactive', 'blue', 'jack', 'harrington'],
    author: 'Jack Harrington',
    author_url: 'https://www.youtube.com/channel/UC6vRUjYqDuoUsYsku86Lrsw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1628640000000,
  },
  {
    link: 'https://youtu.be/cuHDQhDhvPE?t=1038',
    title: 'I built the same app 10 times // Which JS Framework is best?',
    description: 'Solid is featured amongst 10 other frameworks and compared.',
    keywords: ['fireship'],
    author: 'Fireship',
    author_url: 'https://www.youtube.com/channel/UCsBjURrPoezykLs9EqgamOA',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1628640000000,
  },
  {
    link: 'https://www.youtube.com/watch?v=cFasysKU7vk&t=5s',
    title: "React Wednesdays: Let's Learn Solid JS with Ryan Carniato",
    description:
      'On this episode of React Wednesdays we welcome in Ryan Carniato, a member of the Marko team at eBay, and the author of Solid JS.',
    keywords: ['react', 'wednesday'],
    author: 'CodeItLive',
    author_url: 'https://www.telerik.com/react-wednesdays',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1628640000000,
  },
  {
    link: 'https://www.youtube.com/watch?v=2iK9zzhSKo4&t=69s',
    title: 'React Finland 2021: SolidJS - Reactive JSX',
    description:
      'An introduction to SolidJS UI Library. Explore an example to show the similarity and differences between Hook + Virtual DOM versus Reactivity + DOM.',
    keywords: ['react', 'finland'],
    author: 'React Finland',
    author_url: 'https://react-finland.fi/',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1630368000000,
  },
  {
    link: 'https://www.youtube.com/watch?v=PW6Re59Hb-8',
    title: 'AM Coder - SolidJS Todo App for Express/Mongo API',
    description: 'Alex Merced walks us through creating a Solid app with Express and Mongo.',
    keywords: ['express', 'app', 'mongo'],
    author: 'Alex Merced',
    author_url: 'https://www.youtube.com/channel/UCoc4UCEetAt3htM3hV1dQgQ',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational, ResourceCategory.Data, ResourceCategory.UI],
    published_at: 1631059200000,
  },
  {
    link: 'https://www.youtube.com/watch?v=LZc2hSghezM&t=57s',
    title: 'Solid + GraphQL = Realtime Magic',
    description:
      "Let's use the Solid-JS framework to create a todo app using queries, mutations and ",
    keywords: ['graphql', 'queries'],
    author: 'Jack Harrington',
    author_url: 'https://www.youtube.com/channel/UC6vRUjYqDuoUsYsku86Lrsw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational, ResourceCategory.Data],
    published_at: 1630886400000,
  },
  {
    link: 'https://www.youtube.com/watch?v=0zadjVUV7zM',
    title: 'Streaming SolidJS - Context, Async, & Suspense',
    description: 'Ryan talks about context, async and suspense.',
    keywords: ['context', 'transitions', 'suspense', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1631894400000,
  },
  {
    link: 'https://www.youtube.com/watch?v=0zadjVUV7zM',
    title: 'Streaming SolidJS - Server Rendering',
    description: 'Ryan talks about Server Rendering with SolidJS Framework',
    keywords: ['ssr', 'streaming', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1632499200000,
  },
  {
    link: 'https://www.youtube.com/watch?v=b9e7VXs_A4s',
    title: 'Fine-Grained Reactivity',
    description:
      'Ryan goes over the topic of fine-grained reactivity based on my article series and answer any questions along the way.',
    keywords: ['fine-grained', 'reactivity', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1631296862000,
  },
  {
    link: 'https://www.youtube.com/watch?v=jnZmG4hyNas',
    title: 'First look at DOM Expressions',
    description: 'Overview of the universal reactive renderer that powers SolidJS.',
    keywords: ['expressions', 'dom', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1630713600000,
  },
  {
    link: 'https://www.youtube.com/watch?v=P_attYd04-0',
    title: 'Intro to SolidJS in 20 Minutes',
    description: 'Full stack developer walks through SolidJS is 20 minutes.',
    keywords: ['introduction', 'learning'],
    author: 'Alex Merced',
    author_url: 'https://www.youtube.com/channel/UCoc4UCEetAt3htM3hV1dQgQ',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1633369644000,
  },
  {
    link: 'https://www.youtube.com/watch?v=UPhx3OxUH0w',
    title: 'Streaming SolidJS - First look at Astro',
    description: 'Ryan takes a look at what Astro is all about with Solid.',
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    keywords: ['astro', 'streaming', 'ryanstream'],
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational, ResourceCategory.BuildUtilities],
    published_at: 1633110444000,
  },
  {
    link: 'https://www.youtube.com/watch?v=YxroH_MXuhw',
    title: 'Streaming SolidJS: Routing',
    description:
      "Looks at control flow and routing in Solid and the approach we've taken with Solid App Router.",
    keywords: ['introduction', 'control flow', 'routing', 'stream', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational, ResourceCategory.Routers],
    published_at: 1633752000000,
  },
  {
    link: 'https://www.youtube.com/watch?v=Q0mXYbA86Qo',
    title: 'Islands, Partial Hydration, & JavaScript Frameworks',
    description:
      'Ryan explores the ideas of islands, islets, and partial hydration, and look at what frameworks like Marko, Astro, and Qwik are attacking this.',
    keywords: ['islands', 'islets', 'hydration', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational, ResourceCategory.Routers],
    published_at: 1634326849000,
  },
  {
    link: 'https://www.youtube.com/watch?v=Yi_MJ8cVCCs',
    title: 'Streaming SolidJS - Benchmarking and Custom Renderers',
    description:
      'The history of JavaScript framework benchmarking and the new custom renderer API coming in Solid 1.2.0',
    keywords: ['custom render', 'benchmarking', 'performance', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational, ResourceCategory.Routers],
    published_at: 1635047498000,
  },
  {
    link: 'https://www.youtube.com/watch?v=O2kFXlNSdn0',
    title: 'Streaming SolidJS - Netlify and Vercel and Cloudflare, Oh My!',
    description:
      "This stream looks at what deployment is like on different platforms. And reflect on the work we've been doing with adapters in Solid Start.",
    keywords: ['netlify', 'vercel', 'cloudflare', 'deployment', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1636779600000,
  },
  {
    link: 'https://www.youtube.com/watch?v=ZZ-a7B761Ds&list=PLz8Iz-Fnk_eTpvd49Sa77NiF8Uqq5Iykx',
    title: 'Learn With Jason',
    description:
      'In this episode, Ryan Carniato will teach us how to get started with our first SolidJS app!',
    keywords: ['netlify', 'vercel', 'cloudflare', 'deployment', 'ryanstreams'],
    author: 'Jason Lengstorf',
    author_url: 'https://www.youtube.com/channel/UCnty0z0pNRDgnuoirYXnC5A',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1638507600000,
  },
  {
    link: 'https://www.youtube.com/watch?v=Hdc5QqPfFH8&t=21s',
    title: 'Streaming SolidJS - Concurrent Rendering without a Virtual DOM',
    description:
      "I'm no stranger to skeptics. But today I hope to lay to rest the myth that the VDOM is the only game in town.",
    keywords: ['streaming', 'concurrent', 'rendering', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1637367008000,
  },
  {
    link: 'https://www.youtube.com/watch?v=WE5rIOX12gs',
    title: 'Introduction to SolidJS - SolidJS vs ReactJS',
    description:
      'This video is a small introduction to Solid JS framework with a help of a small todo App.',
    keywords: ['intro', 'react'],
    author: 'dotJS',
    author_url: 'https://www.youtube.com/channel/UCcSeQUrdrNObZqyqMD-913g',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1637810770000,
  },
  {
    link: 'https://www.youtube.com/watch?v=wre8TPir36s',
    title: 'Reactive Primitives in Solid JS',
    description:
      'This video is about different SolidJS reactive primitives. How to use them in a an application.',
    keywords: ['intro', 'primitives'],
    author: 'dotJS',
    author_url: 'https://www.youtube.com/channel/UCcSeQUrdrNObZqyqMD-913g',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational, ResourceCategory.Primitives],
    published_at: 1637810770000,
  },
  {
    link: 'https://www.youtube.com/watch?v=Off4L7NJgA0&t=29534s',
    title: 'JS Conf India Online 2021: The Future is Reactive',
    description:
      'Ryan introduces the concept of reactivity and describes why it is the future of UI.',
    keywords: ['netlify', 'jsonf', 'india', 'reactivity', 'ryanstreams'],
    author: 'JSConf India',
    author_url: 'https://www.jsconf.in/',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1638576320000,
  },
  {
    link: 'https://www.youtube.com/watch?v=s_Fs4AXsTnA',
    title: 'Micro-Frontends in Just 10 Minutes',
    description:
      'Take ten minutes to create three applications using Module Federation to create and share a Micro-Frontend between SolidJS and React.',
    keywords: ['micro', 'front-end', 'react', 'module', 'federation'],
    author: 'JSConf India',
    author_url: 'https://www.jsconf.in/',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1634192389000,
  },
  {
    link: 'https://www.youtube.com/watch?v=70w-UoEu3Ss',
    title: 'SolidJS with Ryan Carniato',
    description:
      'Ryan Carniato tells us all about SolidJS, a declarative, efficient, and flexible JavaScript library for building user interfaces.',
    keywords: ['logrocket', 'solid', 'react', 'module', 'federation'],
    author: 'LogRocket',
    author_url: 'https://www.youtube.com/channel/UCktI_HQAkbr-tJbdWnQ_osw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1630482701000,
  },
  {
    link: 'https://www.youtube.com/watch?v=CQm52h3Ukng',
    title: 'A First Look at Remix',
    description: 'Ryan takes a deep dive into Remix.',
    keywords: ['remix', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1638521693000,
  },
  {
    link: 'https://www.youtube.com/watch?v=FB_kBYO_vIw',
    title: 'Compilation in JavaScript Frameworks',
    description: 'Ryan covers the topic of JavaScript compilers.',
    keywords: ['compilers', 'js', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/channel/UCLLVlcmcCP4CUe7xSqVEnxw',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1639126493000,
  },
  {
    link: 'https://www.twitch.tv/videos/1275982315',
    title: 'SolidJS - a Reactive Framework w/ Author Ryan Carniato',
    description: 'Ryan talks about the start of Solid and walks us through why its so special.',
    keywords: ['coderpad', 'reactivity'],
    author: 'CoderPad',
    author_url: 'https://www.twitch.tv/coderpad',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1642791417000,
  },
  {
    link: 'https://www.youtube.com/watch?v=6CnjpXSZXXk',
    title: 'SolidJS loops are better than React',
    description: "A video that compares React Array.map with Solid's <For> component.",
    keywords: ['for', 'loop', 'reactivity'],
    author: 'Basarat Codes',
    author_url: 'https://www.youtube.com/channel/UCGD_0i6L48hucTiiyhb5QzQ',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1642791417000,
  },
  {
    link: 'https://www.youtube.com/watch?v=Jn5e1NYFfN4',
    title: 'Regaining JavaScript Performance in your Website',
    description:
      'PurrfectDev has Ryan Carniato on to talk about SolidJS and performance on your website.',
    keywords: ['for', 'loop', 'reactivity'],
    author: 'PurrfectDev',
    author_url: 'https://codingcat.dev/',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1646203243000,
  },
  {
    link: 'https://www.youtube.com/watch?v=Bwjm4asSAMo',
    title: 'SolidJS with ArcGIS API for JavaScript',
    description: 'Looks at how easy it is to use with the ArcGIS API for JavaScript',
    keywords: ['arcgis', 'rene rubalcave'],
    author: 'Rene Rubalcava',
    author_url: 'https://www.youtube.com/channel/UCo7tc3KZgH4GMUcqcSFBLOQ',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1649400779000,
  },
  {
    link: 'https://www.youtube.com/watch?v=tcwe85p7M9c',
    title: "Petite Solid?! Let's build a Micro View Library",
    description:
      'The question of this functionality in Solid has come up a few times and I thought it would be fun to explore. What this really is, is a throwback to the early days of frontend frameworks.',
    keywords: ['petitsolid', 'small', 'petit', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/c/RyanCarniato9/videos',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1641542174000,
  },
  {
    link: 'https://www.youtube.com/watch?v=lsWXyyEsw7E&t=1838s',
    title: 'Solid Three, Custom Renderers, and SolidStart w/ Nikhil Saraf',
    description:
      "Tonight I'm excited to be joined by the creator of a few really cool projects in the Solid ecosystem and one of main contributors to upcoming SolidStart Metaframework.",
    keywords: ['three', 'three.js', 'custom renderer', 'renderer', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/c/RyanCarniato9/videos',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1643356574000,
  },
  {
    link: 'https://www.youtube.com/watch?v=ZVKHxm1-g3E',
    title: 'SolidScript?! Using Compilation for Syntax',
    description:
      'Everyone seems to have their own preferences when it comes to syntax. Some like it explicit. Some implicit. Fortunately, with the right primitives, it is easy to tailor it to what you want.',
    keywords: ['solidscript', 'compilation', 'syntax', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/c/RyanCarniato9/videos',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1647586574000,
  },
  {
    link: 'https://www.youtube.com/watch?v=REXtIuAJ3dE',
    title: 'Breaking Down the Web /w Dan Jutan',
    description:
      'Dan Jutan, Solid Core Team member in charge of Documentation, joins Ryan to help give context for a lot of the topics he covers on stream.',
    keywords: ['breaking down', 'hydration', 'ssr', 'web', 'streaming', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/c/RyanCarniato9/videos',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1650670987000,
  },
  {
    link: 'https://www.youtube.com/watch?v=iR5T2HefqKk',
    title: 'Breaking Down Hydration w/Dan Jutan',
    description: 'Want to know what Partial, Progressive, and Resumable means?',
    keywords: ['breaking down', 'hydration', 'ssr', 'web', 'streaming', 'ryanstreams'],
    author: 'Ryan Carniato',
    author_url: 'https://www.youtube.com/c/RyanCarniato9/videos',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1651290187000,
  },
  {
    link: 'https://www.youtube.com/watch?v=WSvmEG7HPyE',
    title: "SolidJS - Why Doesn't React Just Work like This",
    description: 'Want to know what Partial, Progressive, and Resumable means?',
    keywords: ['learning', 'starter', 'reactivity', 'planet'],
    author: 'Planet of the Web',
    author_url: 'https://www.youtube.com/channel/UCnd308ZWP--wV2-_j3LZU9A',
    type: ResourceType.Video,
    categories: [ResourceCategory.Educational],
    published_at: 1652280016000,
  },
];

export default videos;
